### ISSUE TITLE
"bootloop" after pulling latest nightly

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#1015]
I just pulled the last nightly.
With this version docspell no longer boots correctly and gets stuck in a "boot loop". Here is the log of the restserver during the boot process:

```docspell-restserver | [main] INFO  d.r.Main - Using given config file: /opt/docspell.conf 
docspell-restserver | [main] INFO  d.r.Main - 
docspell-restserver | ***>  ______                          _ _
docspell-restserver | ***>  |  _  \                        | | |
docspell-restserver | ***>  | | | |___   ___ ___ _ __   ___| | |
docspell-restserver | ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
docspell-restserver | ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
docspell-restserver | ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
docspell-restserver | ***>                      | |
docspell-restserver | ***>                      |_| v0.26.0-SNAPSHOT (#b145378c)
docspell-restserver | ***>  << REST Server >>
docspell-restserver | ***>  Id:       rest1
docspell-restserver | ***>  Base-Url: http://localhost:7880
docspell-restserver | ***>  Database: jdbc:postgresql://db:5432/dbname
docspell-restserver | ***>  Fts:      http://solr:8983/solr/docspell
docspell-restserver | ***>  Config:   /opt/docspell.conf
docspell-restserver | ***>   
docspell-restserver | [io-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations... 
docspell-restserver | [io-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/postgresql) 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.13.0 by Redgate 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.d.b.BaseDatabaseType - Database: jdbc:postgresql://db:5432/dbname (PostgreSQL 13.3) 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary. No failed migration detected. 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.194s). 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.13.0 by Redgate 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.c.DbValidate - Successfully validated 43 migrations (execution time 00:00.077s) 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.c.DbMigrate - Current version of schema "public": 1.24.0 
docspell-restserver | [io-compute-0] INFO  o.f.c.i.c.DbMigrate - Migrating schema "public" to version "1.25.0 - add empty trash" 
postgres_db   | 2021-08-17 05:19:17.420 UTC [63] ERROR:  relation "empty_trash_setting" already exists
postgres_db   | 2021-08-17 05:19:17.420 UTC [63] STATEMENT:  CREATE TABLE "empty_trash_setting" (
postgres_db   |           "cid" varchar(254) not null primary key,
postgres_db   |           "schedule" varchar(254) not null,
postgres_db   |           "created" timestamp not null,
postgres_db   |           foreign key ("cid") references "collective"("cid")
postgres_db   |         )
docspell-restserver | [io-compute-0] ERROR o.f.c.i.c.DbMigrate - Migration of schema "public" to version "1.25.0 - add empty trash" failed! Changes successfully rolled back. 
docspell-restserver | Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.25.0__add_empty_trash.sql failed
docspell-restserver | ---------------------------------------------
docspell-restserver | SQL State  : 42P07
docspell-restserver | Error Code : 0
docspell-restserver | Message    : ERROR: relation "empty_trash_setting" already exists
docspell-restserver | Location   : db/migration/postgresql/V1.25.0__add_empty_trash.sql (/opt/file:/opt/docspell-restserver-0.26.0-SNAPSHOT/lib/com.github.eikek.docspell-store-0.26.0-SNAPSHOT.jar!/db/migration/postgresql/V1.25.0__add_empty_trash.sql)
docspell-restserver | Line       : 1
docspell-restserver | Statement  : CREATE TABLE "empty_trash_setting" (
docspell-restserver |   "cid" varchar(254) not null primary key,
docspell-restserver |   "schedule" varchar(254) not null,
docspell-restserver |   "created" timestamp not null,
docspell-restserver |   foreign key ("cid") references "collective"("cid")
docspell-restserver | )
docspell-restserver | 
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271)
docspell-restserver |   at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
docspell-restserver |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:70)
docspell-restserver |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
docspell-restserver |   at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
docspell-restserver |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:217)
docspell-restserver |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:168)
docspell-restserver |   at org.flywaydb.core.Flyway.execute(Flyway.java:584)
docspell-restserver |   at org.flywaydb.core.Flyway.migrate(Flyway.java:168)
docspell-restserver |   at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:42)
docspell-restserver |   at delay @ docspell.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:21)
docspell-restserver |   at map @ docspell.store.impl.StoreImpl.migrate(StoreImpl.scala:30)
docspell-restserver |   at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
docspell-restserver |   at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
docspell-restserver |   at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
docspell-restserver |   at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1050)
docspell-restserver |   at >>$extension @ fs2.Pull$.goFlatMapOut$1(Pull.scala:1005)
docspell-restserver |   at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:898)
docspell-restserver |   at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:898)
docspell-restserver |   at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:898)
docspell-restserver |   at delay @ doobie.hikari.HikariTransactor$.$anonfun$newHikariTransactor$4(HikariTransactor.scala:58)
docspell-restserver |   at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
docspell-restserver |   at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
docspell-restserver |   at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
docspell-restserver |   at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1050)
docspell-restserver |   at >>$extension @ fs2.Pull$.goFlatMapOut$1(Pull.scala:1005)
docspell-restserver | Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.25.0__add_empty_trash.sql failed
docspell-restserver | ---------------------------------------------
docspell-restserver | SQL State  : 42P07
docspell-restserver | Error Code : 0
docspell-restserver | Message    : ERROR: relation "empty_trash_setting" already exists
docspell-restserver | Location   : db/migration/postgresql/V1.25.0__add_empty_trash.sql (/opt/file:/opt/docspell-restserver-0.26.0-SNAPSHOT/lib/com.github.eikek.docspell-store-0.26.0-SNAPSHOT.jar!/db/migration/postgresql/V1.25.0__add_empty_trash.sql)
docspell-restserver | Line       : 1
docspell-restserver | Statement  : CREATE TABLE "empty_trash_setting" (
docspell-restserver |   "cid" varchar(254) not null primary key,
docspell-restserver |   "schedule" varchar(254) not null,
docspell-restserver |   "created" timestamp not null,
docspell-restserver |   foreign key ("cid") references "collective"("cid")
docspell-restserver | )
docspell-restserver | 
docspell-restserver |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:277)
docspell-restserver |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:224)
docspell-restserver |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128)
docspell-restserver |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
docspell-restserver |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
docspell-restserver |   at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
docspell-restserver |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271)
docspell-restserver |   at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
docspell-restserver |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:70)
docspell-restserver |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
docspell-restserver |   at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
docspell-restserver |   at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
docspell-restserver |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:217)
docspell-restserver |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:168)
docspell-restserver |   at org.flywaydb.core.Flyway.execute(Flyway.java:584)
docspell-restserver |   at org.flywaydb.core.Flyway.migrate(Flyway.java:168)
docspell-restserver |   at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:42)
docspell-restserver |   at cats.effect.IOFiber.runLoop(IOFiber.scala:319)
docspell-restserver |   at cats.effect.IOFiber.execR(IOFiber.scala:1151)
docspell-restserver |   at cats.effect.IOFiber.run(IOFiber.scala:128)
docspell-restserver |   at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:359)
docspell-restserver | Caused by: org.postgresql.util.PSQLException: ERROR: relation "empty_trash_setting" already exists
docspell-restserver |   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
docspell-restserver |   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
docspell-restserver |   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
docspell-restserver |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
docspell-restserver |   at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
docspell-restserver |   at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
docspell-restserver |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212)
docspell-restserver |   
... 25 more
docspell-restserver exited with code 1
```

**Comment by eikek** [comment]
Oh strange, why did this table already exist?
```
021-08-17 05:19:17.420 UTC [63] ERROR:  relation "empty_trash_setting" already exists
```
Can you try to drop this table?

**Comment by monnypython** [comment]
Sorry, but i can't login to database:

My docker-compose.yml looks like this:

````
 db:
    image: postgres:13.3
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - docspell-postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
````


## Start container:
`docker-compose up -d db`
![image](https://user-images.githubusercontent.com/42573701/129691734-5d7d4110-eb1b-49c9-9d10-9ac8664bb1f4.png)

## go into container:
`docker exec -it postgres_db bash `

![image](https://user-images.githubusercontent.com/42573701/129691899-1a57ef3f-2174-4ef5-856c-0720c3139a88.png)

**Comment by eikek** [comment]
> I had already pulled a nightly last night and then this morning the new one to try out the colored, active filters. Maybe that's where the error comes from?

Yes probably. I must have published an intermediate version of the migration. But this can happen for the nightlies. I only test if an upgrade works across releases.

**Comment by monnypython** [comment]
OK. Thank you!

**Comment by monnypython** [comment]
Mmhh... 
Now I have restarted again and the same error occurs again. So I have to manually delete the table before every restart.

**Comment by eikek** [comment]
Ok, it seems the flyway migration table is a bit confused. You could try to remove the table again and all related changesets from the `flyway_schema_history` table. I think something like this should work: `DELETE FROM flyway_schema_history WHERE version LIKE '1.25%'` ; then drop the table again and try to startup. When you look at the schema_history table, every version should occur exactly once. When using nightlies this might not be the case and is ok, but when using only releases this should be true.

**Comment by monnypython** [comment]
Thank you for your help!
Unfortunately I was unsuccessful. Deleting the entries in the "flyway_schema_history" table and deleting the "empty_trash_setting" table only help when you start docspell for the first time.

At the moment, every time the service is restarted, additional entries are made in the "flyway_schema_history". The "empty_trash_setting" table is created again and again.

![image](https://user-images.githubusercontent.com/42573701/129854315-30a63bfb-54c9-4424-84a5-aa1d0ba363b0.png)

As you described the problem is probably due to the nightly updates. Since my server is seldom restarted and docspell runs 24/7, it's not that bad for me at first. Will this (my) problem be resolved with the update to the next major version?
If so, maybe the ticket can be closed.

**Comment by eikek** [comment]
Hm, strange. The problem is not automatically resolved when using the nightly versions. I try to not let this happen, but there's no guarantee. I find it strange, because I used new changesets exactly because of this problem (I actually never edit existing changesets). I can't really explain why this happens to you. When I'm developing, I restart the app countless times and it didn't occur to me 😕 Otoh, this is the kind of problem that *can* happen unfortunately with the nightly packages.

The solution is to restore the state before the db migration (so removing all flyway entries for the 1.25.x version and its outcome, which is in this case the new table empty_trash_setting). Then a restart should create one entry for each changeset. From your screenshot it seems to me that a previous version of docspell was started at some point? Is your screenshot the result from a restart *after* removing all entries regarding versions 1.25.x and the empty_trash_setting table?

**Comment by monnypython** [comment]
> Is your screenshot the result from a restart after removing all entries regarding versions 1.25.x and the empty_trash_setting table?
>
See Summary below...

Here again the exact course of the procedure (also for me to understand 🤨):

## 1. Stop docker-compose
`docker-compose stop`

## 2. Start db-container and login to docker container of postgres
`docker-compose up -d db`
`docker exec -it postgres_db psql -U dbuser -d dbname`
### Delete entrys 
`DELETE FROM flyway_schema_history WHERE version LIKE '1.25%';`
### Drop table
`DROP TABLE "empty_trash_setting"; `

### Current Status
flyway...
![image](https://user-images.githubusercontent.com/42573701/129886958-178f2943-d716-4e68-885f-3cb8d5c4f536.png)
tables
![image](https://user-images.githubusercontent.com/42573701/129887065-f92717aa-8d50-42ca-8427-44adff9c2707.png)

## 3. Start docker-compose
`docker-compose up -d` (Restserver starts correctly)

### Current Status
flyway...
![image](https://user-images.githubusercontent.com/42573701/129887485-02783676-7c2b-41bf-ad24-5a0a48f58793.png)
tables
![image](https://user-images.githubusercontent.com/42573701/129887417-c7214488-9c9c-4161-8e4d-62af198c235f.png)

## 4. Stop Server
`docker-compose stop`
## 5. Start Server
`docker-compose up -d` (Restserver won`t start; Website not reachable)

flyway...
![image](https://user-images.githubusercontent.com/42573701/129888377-e4dc6999-504d-4d85-9a76-bdd0d369de74.png)
tables
(as before)

## 6. Stop Server
`docker-compose stop`

### flyway...
(do nothing)

### Drop table
`DROP TABLE "empty_trash_setting"; `

## 5. Start Server
`docker-compose up -d` (Restserver start; Website is reachable)

flyway...
![image](https://user-images.githubusercontent.com/42573701/129889114-a4b4a6ed-c538-4c18-b845-cc7a05847ec9.png)
tables
![image](https://user-images.githubusercontent.com/42573701/129889172-14166a5e-52a1-4fa5-ad36-8d2f78c05d54.png)

---

### Summary

So if only the "empty_trash_" table is deleted (and not the flyway-entries "1.25.*"), additional entries are created in the "flyway" table each time the server starts.
The server starts when empty_trash is not there, no matter how many entries there are in flyway ... or?

**Comment by eikek** [comment]
Woah… this is really strange! Currently, this almost looks like a bug in flyway. Why would it go do something if the changesets have already been run? And the checksum value is also the same in all cases. And why does this behavior only affect the 1.25.x versions… I need to take a deeper look at this, hopefully I can reproduce it. I think there was a dependency update of flyway recently…

**Comment by eikek** [comment]
I'm sorry, I can't reproduce it. I used docker-compose with nightly packages. Here is what I did:

### Start all

``` shell
> docker-compose up -d
```

Checked that it works.

### Stop all and start only postgres

``` shell
> docker-compose down
> docker-compose up db
```
 
Mapped port 5434 to psql container. Log in to postgres and look at the data:

``` shell
> psql -h localhost -p 5434 -U dbuser dbname
```

Table is there and flyway history looks good.

``` 
dbname=# \d empty_trash_setting;
                   Table "public.empty_trash_setting"
  Column  |            Type             | Collation | Nullable | Default
----------+-----------------------------+-----------+----------+---------
 cid      | character varying(254)      |           | not null |
 schedule | character varying(254)      |           | not null |
 created  | timestamp without time zone |           | not null |
 min_age  | bigint                      |           | not null |
Indexes:
    "empty_trash_setting_pkey" PRIMARY KEY, btree (cid)
Foreign-key constraints:
    "empty_trash_setting_cid_fkey" FOREIGN KEY (cid) REFERENCES collective(cid)


dbname=# select * from flyway_schema_history where version like '1.25%';
 installed_rank | version |         description          | type |                  script                   |  checksum  | installed_by |        installed_on        | execution_time | success
----------------+---------+------------------------------+------+-------------------------------------------+------------+--------------+----------------------------+----------------+---------
             35 | 1.25.0  | add empty trash              | SQL  | V1.25.0__add_empty_trash.sql              | -943147294 | dbuser       | 2021-08-19 22:30:57.10569  |             10 | t
             36 | 1.25.1  | fix periodic submitter value | SQL  | V1.25.1__fix_periodic_submitter_value.sql | 1797712347 | dbuser       | 2021-08-19 22:30:57.121643 |              2 | t
             37 | 1.25.2  | add trash min age            | SQL  | V1.25.2__add_trash_min_age.sql            |  396118090 | dbuser       | 2021-08-19 22:30:57.129152 |              3 | t
(3 rows)
```

Then deleted the table and corresponding changesets:

``` sql
dbname=# DELETE FROM flyway_schema_history WHERE version like '1.25%';
DELETE 3
dbname=# DROP TABLE empty_trash_setting;
DROP TABLE
```


### Restart again and again

Restarted several times via `docker-compose down/up -d` and `docker-compose stop/start`. The database didn't change.

**Comment by monnypython** [comment]
Thank you for your efforts! 
Then it seems to be an isolated case.
Do you think I can set up the docker-compose again from latest stable and restore my database in the new system?

**Comment by eikek** [comment]
Yes, you can remove (again :)) the `empty_trash_setting` table and all changesets from 1.25.x. Then the latest stable release should start up fine. But… actually also the nightly should startup fine 😕 . I'd create a db dump just in case; but you probably already have
