### ISSUE TITLE
Searching contents results in a HTTP 500 error

### ISSUE THREAD

**Issue by hardysim** [eikek/docspell#1020]
I'm testing out docspell and uploaded some PDFs. They show up and I can search for their title just fine using the "Search in names" feature. But when trying to search via "Content search" the request fails with an HTTP 500 and nothing happens.

![image](https://user-images.githubusercontent.com/3737512/130193554-c2fbc977-00f1-420b-b580-964f1f8cc3b6.png)

This seem to happen only sometimes or only for some queries. Other times, the request gets back with a 200 but with no result even when I search for content wich is recognized because I can see it under "Extracted Meta Data" > "Content".

![image](https://user-images.githubusercontent.com/3737512/130193670-0ab67f71-4db1-4773-83aa-96f894bfb48c.png)

I get a result if I do a name-search for `klarenthal`  but get a 500 / no result on a content-search.

---

Any ideas on the cause? I'm running docspell via docker-compose on a QNAP NAS.
Is the system supposed to show an error or any kind of feedback if no results are shown?

**Comment by eikek** [comment]
Hi @hardysim , this sounds like an issue with solr. Can you get to some log output - maybe the restserver one and maybe also the one from solr? A 500 response should produce some error logs at the docspell-restserver component.

**Comment by hardysim** [comment]
Sure, here you go (I hope I got the correct pieces since the log does not align very well).

restserver
```
[io-compute-1] DEBUG d.b.o.OSimpleSearch - Using index only search: Some(klarenthal) 
                                                                                                 [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats 
                                            [io-compute-0] INFO  o.h.s.m.Logger - service raised an error: class org.http4s.client.UnexpectedStatus 
              [io-compute-0] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/searchStats from 192.168.0.140 
  org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request for request POST http://docspell-solr:8983/solr/docspell/query
      [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/search 
                                                                                  [io-compute-0] INFO  o.h.s.m.Logger - service raised an error: class org.http4s.client.UnexpectedStatus 
                                                    [io-compute-0] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/search from 192.168.0.140 
                                   org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request for request POST http://docspell-solr:8983/solr/docspell/query
```

solr
```
2021-08-23 07:13:34.765 INFO  (qtp380812044-21) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/query params={} status=400 QTime=3
                                                                                                            2021-08-23 07:14:08.657 ERROR (qtp380812044-20) [   x:docspell] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
                                                                                                                                                                                                                                                                        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1318)
                                                                                at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:494)
                                                                                                                                                                                        at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:86)
                                                        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:192)
                                                                                                                                at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:259)
                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:534)
                                at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)
                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1109)
                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:832)
                                        at org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)
                                                                                                                at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
                                                                                                                                                                                        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
                                                                                                                                                                                                                                                                at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)
                                                        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
                                                                                                                                at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:270)
                        at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
                                                                                                at org.apache.solr.search.QParser.getQuery(QParser.java:174)
                                                                                                                                                                at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)
                                                                                                                                                                                                                                                        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:334)
                                                                        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
                                                                                                                                                                        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2637)
                                                                                                                                                                                                                                        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:794)
                                at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:567)
                                                                                                        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427)
                                                                                                                                                                                                at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:357)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
                                                                                        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
                                                                                                                                                                                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
                                                                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
                                                                        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
                                                                                                                                                        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
                                                        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
                                                                                                                                                                                                                                        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
                                                                                                                                        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
                                                                                                                                                                                                                        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
                                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
                                                                                                                        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
                        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
                                                                                                                                at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)
                                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
                                                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                                                                                                        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
                                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                        at org.eclipse.jetty.server.Server.handle(Server.java:516)
                                                                                                        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
                                                                                                                                                                                        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
                                                                                                                                                                                                                                                                at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
                                                        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
                                                                                                                                        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
                                                                                                                                                                                                                                        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
                                at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
                                                                                                        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
                                                                                                                                                                                                        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
                        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
                                                                                                                        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
                                                                                                                                                                                                                at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
                                                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
                                                                                                                                        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
                                                                                                                                                                                                                                        at java.base/java.lang.Thread.run(Unknown Source)

         2021-08-23 07:14:08.658 INFO  (qtp380812044-20) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/query params={} status=400 QTime=3
                                                                                                                                                            2021-08-23 07:14:08.666 ERROR (qtp380812044-17) [   x:docspell] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
                                        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1318)
                                                                                                                                at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:494)
                                                                                                                                                                                                                                        at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:86)
                                                                                                        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:192)
                                                                                                                                                                                at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:259)
                                                                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:534)
                                                                                at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)
                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1109)
                                                                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:832)
                                                                                        at org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)
                                                                                                                                                                at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
                                                                                                                                                                                                                                        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
                                at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)
                                                                                                        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
                                                                                                                                                                                at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
                                                                                                                                                                                                                                                                at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:270)
                                                                        at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
                                                                                                                                                at org.apache.solr.search.QParser.getQuery(QParser.java:174)
                                                                                                                                                                                                                at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)
                        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:334)
                                                                                                                        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
                                                                                                                                                                                                                        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2637)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:794)
                                                                                at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:567)
                                                                                                                                                        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427)
                                                                                                                                                                                                                                                at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:357)
                                                        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
                                                                                                                                        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
                                                                                                                                                                                                                                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
                                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
                                                                                                                        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
                                                                                                                                                                                                        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
                                                                                                        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
                                                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
                                                                                                                                                                                        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
                                                                                                                                                                                                                                                                        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
                                                                                                                                                                        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
                                                                                                                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
                                                                        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
                                                                                                                                                                                at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)
                                                                                                                                                                                                                                                                               at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
                                                                                        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                                                                                                                                                at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
                                                                                                                                                                                                                                                                        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                                                at org.eclipse.jetty.server.Server.handle(Server.java:516)
                                                                                                                                                at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
                                                                                                                                                                                                                                at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
                        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
                                                                                                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
                                                                                                                                                                                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
                                                                                                                                                                                                                                                                               at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
                                                                        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
                                                                                                                                                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
                                                                                                                                                                                                                                                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
                                                                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
                                                                                                                                                                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
                                                                                                                                                                                                                                                        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
                                                                                        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
                                                                                                                                                                                at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
                                                                                                                                                                                                                                                                               at java.base/java.lang.Thread.run(Unknown Source)

                                                2021-08-23 07:14:08.667 INFO  (qtp380812044-17) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/query params={} status=400 QTime=2
```

**Comment by eikek** [comment]
Oh strange this formatting! But it looks to me as if the index is not correctly setup. You can try to re-create the entire index. Easiest way is to use the cli tool for this and run `dsc admin recreate-index` . You need to configure an "admin secret" in docspell's config file.

**Comment by eikek** [comment]
Closing this row; feel free to reopen if there's interest.
