### ISSUE TITLE
SQL Error after update to 0.27.0

### ISSUE THREAD

**Issue by r4tze** [eikek/docspell#1091]
After I made the update to 0.27.0 I face the following error:

```
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.26.3__filestore.sql failed
Sep 27 12:40:19 docspell-server docspell-joex[19374]: ---------------------------------------
Sep 27 12:40:19 docspell-server docspell-joex[19374]: SQL State  : 42000
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Error Code : 1064
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Message    : (conn=688) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Location   : db/migration/mariadb/V1.26.3__filestore.sql (/usr/share/docspell-joex/file:/usr/share/docspell-joex/lib/com.github.eikek.docspell-store-0.27.0.jar!/db/migration/mariadb/V1.26.3__filestore.sql)
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Line       : 4
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Statement  : ALTER TABLE `filemeta`
Sep 27 12:40:19 docspell-server docspell-joex[19374]: RENAME COLUMN `id` TO `file_id`
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:277)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:224)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:154)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.Flyway$1.execute(Flyway.java:219)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.Flyway.execute(Flyway.java:586)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:42)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at cats.effect.IOFiber.runLoop(IOFiber.scala:319)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at cats.effect.IOFiber.execR(IOFiber.scala:1169)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at cats.effect.IOFiber.run(IOFiber.scala:128)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:410)
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Caused by: java.sql.SQLSyntaxErrorException: (conn=688) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:504)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         ... 25 more
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         ... 29 more
Sep 27 12:40:19 docspell-server docspell-joex[19374]: Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
Sep 27 12:40:19 docspell-server docspell-joex[19374]:         ... 30 more
Sep 27 12:40:19 docspell-server systemd[1]: docspell-joex.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 12:40:19 docspell-server systemd[1]: docspell-joex.service: Failed with result 'exit-code'.
```

All I did, was downloading the .deb files and executing them. I tried it with replacing the config files and editing it afterwards and I tried it with keeping the files.

**Comment by eikek** [comment]
Hi @r4tze , this is not solr this time, but the sql migration. Which version of MariaDB do you use?

**Comment by r4tze** [comment]
Hi @eikek. I'm using the UbuntuServer 20.04 MariaDB version. It's MariaDB 10.3.31
Should I update to the version from the original repository?

**Comment by eikek** [comment]
You did everything right! I think I'm using a newer syntax for renaming the columns. I wasn't aware of this, sadly…. It has been added in version 10.5.2 as I just found out [here](https://mariadb.com/kb/en/alter-table/#rename-column).

The easiest way would be to upgrade to this version of MariaDB 10.5.x (I tested with 10.5.10). I think currently 10.6 is already out, so maybe that's not even too bad to upgrade. Ubuntu 20.04 also is more than a year old :) 

If that's not possible, I can try to create some SQL commands that you need to run against the database in order to do this migration.

**Comment by r4tze** [comment]
Thanks for the suggestion! After an update to the 10.6 the migration was successful and the docspell services are running well.. 
Thank you for your kind help!
