### ISSUE TITLE
Docspell Restserver v0.28.0 breaks with MariaDB v10

### ISSUE THREAD

**Issue by Cruguah** [eikek/docspell#1146]
I've just installed docspell restserver v0.28.0, based on MariaDB v10.
As soon as I start the restserver the following error shows up in the log and the docspell rest server goes down:

2021-10-31 11:53:39	stdout	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:504)
2021-10-31 11:53:39	stdout	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
2021-10-31 11:53:39	stdout	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
2021-10-31 11:53:39	stdout	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
2021-10-31 11:53:39	stdout	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
2021-10-31 11:53:39	stdout	Caused by: java.sql.SQLSyntaxErrorException: (conn=581) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
2021-10-31 11:53:39	stdout	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:410)
2021-10-31 11:53:39	stdout	at cats.effect.IOFiber.run(IOFiber.scala:132)
2021-10-31 11:53:39	stdout	at cats.effect.IOFiber.afterBlockingSuccessfulR(IOFiber.scala:1208)
2021-10-31 11:53:39	stdout	at cats.effect.IOFiber.runLoop(IOFiber.scala:319)
2021-10-31 11:53:39	stdout	at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:42)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.Flyway.migrate(Flyway.java:121)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:208)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.Flyway$1.execute(Flyway.java:121)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:138)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:138)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:57)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:58)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:69)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
2021-10-31 11:53:39	stdout	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)

It seems to have a syntax problem with the upgrade script.

Can you fix this? At this moment i can't use my docspell environment...

Kind regards.

**Comment by eikek** [comment]
Hi @Cruguah oh, this is strange! Which version of MariaDB is this exacty? Did it work with this mariadb version in 0.27.0 or are you maybe upgrading from an earlier version? I tested it with MariaDB 10.5.12 and 10.5.10.

**Comment by eikek** [comment]
Ah, I think it is probably this: #1091 - you need at least MariaDB 10.5.2 :/

**Comment by Cruguah** [comment]
I use MariaDB on my Synology NAS so I've checked the version of MariaDB and it is 10.3.29 (which is the latest version on Synology)
I've digged into your sourcecode, found the migration, and applied it manualy succesfully. Then I could mark the migration as done.
After that I could start the docspell rest server succesfully.

Thanks for your support

**Comment by eikek** [comment]
That's great - 👍🏼 thanks for the update.
