### ISSUE TITLE
Message    : ERROR: relation "notification_channel_mail" already exists

### ISSUE THREAD

**Issue by Mioone** [eikek/docspell#1351]
Hi There,

After enabling "Watchtower", who is update my DocSpell Docker Environment, the RestServer dosn´t comes up anymore.
I try with an Image before docspell/restserver , Tag: 30.1 and after Tag:"Nightly" with the same Error.

Is there any known Migrationsproblems ?
What can i do?

regards

Peter

SQL State  : 42P07
Error Code : 0
Message    : ERROR: relation "notification_channel_mail" already exists
Location   : db/migration/postgresql/V1.29.1__notification.sql (/opt/file:/opt/docspell-restserver-0.31.0/lib/com.github.eikek.docspell-store-0.31.0.jar!/db/migration/postgresql/V1.29.1__notification.sql)
Line       : 1
Statement  : create table "notification_channel_mail" (
  "id" varchar(254) not null primary key,
  "uid" varchar(254) not null,
  "conn_id" varchar(254) not null,
  "recipients" varchar(254) not null,
  "created" timestamp not null,
  foreign key ("uid") references "user_"("uid") on delete cascade,
  foreign key ("conn_id") references "useremail"("id") on delete cascade
)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:382)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:138)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:138)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:42)
	at delay @ docspell.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:21)
	at map @ docspell.store.impl.StoreImpl.migrate(StoreImpl.scala:31)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.29.1__notification.sql failed

**Comment by eikek** [comment]
Hey, this can happen when a downgrade was attempted. The migration can only go forward. Can it be that you tried 0.29.0 once and then switched to an earlier version?

I think we need to clean it up manually. I can give you SQL statements that you need to run against the database. Basically we need to revert all changes from the migrations [V1.29.1](https://github.com/eikek/docspell/blob/master/modules/store/src/main/resources/db/migration/postgresql/V1.29.1__notification.sql) until [V1.31.1](https://github.com/eikek/docspell/blob/master/modules/store/src/main/resources/db/migration/postgresql/V1.31.1__gotify_prio.sql) and then start docspell again. I'm a bit short on time this weekend, I'll try to get back in the next days. This will remove notification data (should you have any), though - not sure how important that is to you, but usually this can be easily added again.

Regarding watchtower: Of course this is very convenient to have automatic updates. In case of docspell I would rather not recommend it. The reason is that downgrading is not possible automatically and so I would always create a database backup before upgrading. If that can be included in the watchtower upgrade scripts - that would be great! Alternatively you can get notified via e-mail by docspell once a new version is released and do the steps manually then.

**Comment by eikek** [comment]
Hi @Mioone , to solve the bad migration state, you can try running the following statements against your database. Obviously they delete stuff - i.e. it deletes all notification hooks and channels that may exist! A backup is recommended, as always when running changes directly on the database.

First, stop all docspell containers. Then start the database container only, for example via `docker-compose up -d -- db`. Then run the sql script below. You should get a postgres session with ` docker exec -it postgres_db psql -U dbuser dbname` where you can paste the script below. Afterwards start docspell as usual. It then should forward the schema to the current version. Hope this helps!

```sql
-- Revert for 1.32.x
drop table if exists "notification_hook_channel";

-- Nothing to revert for 1.31.1
-- Revert 1.31.0
drop table if exists "query_bookmark";

-- Revert 1.30.0
drop table if exists "client_settings_collective";
alter table "client_settings_user" rename to "client_settings";

-- Revert 1.29.1
drop table if exists "notification_channel_mail";
drop table if exists "notification_channel_gotify";
drop table if exists "notification_channel_matrix";
drop table if exists "notification_channel_http";
drop table if exists "notification_hook_event";
drop table if exists "notification_hook";

-- Revert migration version numbers
delete from "flyway_schema_history" where version in ('1.29.1', '1.29.2', '1.30.0', '1.31.0', '1.31.1', '1.32.0', '1.32.1', '1.32.2');
```

**Comment by eikek** [comment]
Closing for now. You can reopen if there is something left
