### ISSUE TITLE
Mail import failed: "Could not store file for processing!"

### ISSUE THREAD

**Issue by J-Brill** [eikek/docspell#1360]
I recently set up docspell on my home server. 
This week I wanted to import invoices etc. from my mail account.
After manually pre-sorting the mails (importing 15000 mail at once is not the best idea ^^) the import worked really well except for some invoices which were moved to the specified target folder but not processed.

I found this in the joex container logs for one of these mails:
```
level=DEBUG thread=io-compute-2 logger=d.j.s.LogSink message=">>> 2022-02-09T18:18:06.591265Z Debug HTZFGbWMn.../jb-docs/scan-mailbox/Low: Submitting mail 'Tankrechnung Rechnungs-Nr.: 000245'"

level=INFO  thread=io-compute-1 logger=d.b.ops.OUpload message="Receiving file File(Some(Tankrechnung Rechnungs-Nr.: 000245.eml),Some(MimeType(message,rfc822,None)),Stream(..))"

level=DEBUG thread=io-compute-1 logger=d.s.f.FileStore message="Inserting data for id 5DAgVNnHmMxcCtbqHCQbgHExQkKCCDCY7mUSG4mJHU3y"

level=WARN  thread=io-compute-17 logger=d.b.ops.OUpload message="Could not store file for processing!"

jakarta.mail.internet.AddressException: Extra route-addr

	at jakarta.mail.internet.InternetAddress.parse(InternetAddress.java:834)

	at jakarta.mail.internet.InternetAddress.parse(InternetAddress.java:728)

	at jakarta.mail.internet.InternetAddress.<init>(InternetAddress.java:95)

	at emil.javamail.conv.BasicEncode.$anonfun$mailAddressEncode$1(BasicEncode.scala:23)

	at emil.javamail.conv.Conv$.emil$javamail$conv$Conv$$$anonfun$apply$1(Conv.scala:18)

	at emil.javamail.conv.Conv$$anonfun$apply$2.convert(Conv.scala:18)

	at emil.javamail.conv.BasicEncode.$anonfun$mailHeaderEncode$4(BasicEncode.scala:96)

	at scala.Option.map(Option.scala:242)

	at emil.javamail.conv.BasicEncode.$anonfun$mailHeaderEncode$1(BasicEncode.scala:96)

	at emil.javamail.conv.MsgConv$.$anonfun$apply$3(Conv.scala:29)

	at emil.javamail.conv.BasicEncode.$anonfun$mailEncode$11(BasicEncode.scala:157)

	at map @ emil.javamail.conv.BasicEncode.$anonfun$mailEncode$10(BasicEncode.scala:156)

	at map @ emil.javamail.conv.BasicEncode.$anonfun$mailEncode$10(BasicEncode.scala:156)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at modify @ fs2.internal.Scope.close(Scope.scala:262)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)

	at as @ docspell.joex.Main$.$anonfun$run$9(Main.scala:47)

	at get @ fs2.internal.Scope.openScope(Scope.scala:281)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)

level=DEBUG thread=io-compute-8 logger=d.j.s.LogSink message=">>> 2022-02-09T18:18:06.605069Z Debug HTZFGbWMn.../jb-docs/scan-mailbox/Low: Post handling mail: Tankrechnung Rechnungs-Nr.: 000245 - moving to folder: 1_Docspell Done"
```

I also downloaded the mail via Mozilla Thunderbird as an .eml file and ingested it into docspell through a consume directory.
With this method the import was processed without errors.

**Comment by eikek** [comment]
Thank you for the report! Can it be that this mail contains some "weird" email addresses, like "Undisclosed recipients" or something like this?

**Comment by J-Brill** [comment]
The mail is sent out automatically each month by a customer management software via a strato.de hosted (reputable german hosting service) mail address.
I couldn't find anything hinting towards a bcc or any undisclosed recipients, but maybe that info is not available in the mail-source?

The only "weird" thing i could find is that they use <my-email>@gmail.com but i didn't convert it to a gmail address yet and am still using <my-email>@googlemail.com.

**Comment by eikek** [comment]
Ok, thanks! Hm.. it looks from the trace as if the `Sender` header is affected. Since this is sensible data, could you maybe replace every letter in that address with some constant one - but leaving other characters (i.e. spaces and brackets etc) in place? You should see it in the mail source - it may not be visible in mail clients. That would help to reproduce this error.

**Comment by J-Brill** [comment]
Here is a complete source of one of the mails.
I replaced all (maybe too much ^^) sensible data with ||descriptive-name-here||

[not_proccessed_mail.txt](https://github.com/eikek/docspell/files/8036302/not_proccessed_mail.txt)

**Comment by eikek** [comment]
Thank you! Unfortunately, I don't see it :) I'm looking at this line:
```
Sender: ||company-name|| <||company/sender||@||strato-hosted-domain||>
```
Is there anything interesting - whitespace or non-alpha chars or so in "company/sender" or "company-name"? Interestingly it seems that the `From:` address was successful, but `Sender:` not. But apart from the quotes they seem to be the same address, right?

**Comment by J-Brill** [comment]
company-name = "Stringa Stringb", there is a whitespace but no non-alpha chars like öäü or any other special chars.
company/sender = "stringc-stringd", two strings separated by a dash.

A full version of that line is (excluding ""): "Sender: Stringa Stringb <stringc-stringd@domain.tld>"

**Comment by eikek** [comment]
Thank you so much! I'm afraid I can't reproduce it. There is probably something else transferred we can't see, or I'm completely on the wrong track. I'll try to find out more, otherwise it is possible to ignore any errors here. Just rather like to know what is really going on :).

**Comment by J-Brill** [comment]
Since I have an easy workaround (download email as .eml --> consume directory) its no major concern anyway.
But thanks for the fast help and your awesome work :)

**Comment by eikek** [comment]
I tried to reproduce it but failed. I'm sorry to say, I think I can't do anything about it :(. I will add more logging in the next release hoping there is more information next time.

**Comment by J-Brill** [comment]
Alright. I'll try the import with those emails again in the next release and provide the logs here. Maybe that will help :)

**Comment by J-Brill** [comment]
Just upgraded to 0.33.0 and the import of one of the mails that failed previously works now :)
Thanks again for your work!

**Comment by eikek** [comment]
Thanks for the update. Now that is surprising - but good news 😄
