### ISSUE TITLE
Upgrade with DB-Migration not successfull

### ISSUE THREAD

**Issue by Madnex** [eikek/docspell#1511]
Hi! I tried to upgrade from Docspell v0.30.1 with postgres 11.7 to v0.34.0 with postgres 14.2. I run into the following error:

```
Apr 12, 2022 10:33:54 AM org.jline.utils.Log logr

WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2022.04.12 10:33:53:511 io-compute-2 INFO docspell.config.ConfigFactory.default:44
    Using config from environment variables!
2022.04.12 10:33:56:0000 [io-comp...] [INFO ] docspell.restserver.Main.run:34 - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.34.0 (#c6da3eb0)
***>  << REST Server >>
***>  Id:       rest1
***>  Base-Url: http://localhost:7880
***>  Database: jdbc:postgresql://db:5432/dbname
***>  Fts:      Solr(http://docspell-solr:8983/solr/docspell)
***>  Config:   
***>  FileRepo: DefaultDatabase(true)
***>  
2022.04.12 10:33:59:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:37 - Creating Flyway for: List(classpath:db/fixups/postgresql, classpath:db/fixups/common)
2022.04.12 10:33:59:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:64 - !!! Running fixup migrations
2022.04.12 10:33:59:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.4 by Redgate
2022.04.12 10:33:59:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.4
2022.04.12 10:33:59:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - 
2022.04.12 10:33:59:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:postgresql://db:5432/dbname (PostgreSQL 14.2)
2022.04.12 10:33:59:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 2 migrations (execution time 00:00.046s)
2022.04.12 10:33:59:0007 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1
2022.04.12 10:33:59:0008 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema "public" to version "1.33.0 - fix reorganize files"
2022.04.12 10:33:59:0009 [io-comp...] [INFO ] org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor - DB: table "valid_file_ids" does not exist, skipping
2022.04.12 10:33:59:0010 [io-comp...] [INFO ] org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor - DB: table "obsolete_files" does not exist, skipping
2022.04.12 10:33:59:0011 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema "public" to version "1.33.0 - fix reorganize files" failed! Changes successfully rolled back.
2022.04.12 10:34:00:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.33.0__fix_reorganize_files.sql failed
--------------------------------------------------
SQL State  : 42703
Error Code : 0
Message    : ERROR: column "file_id" does not exist
  Position: 36
Location   : db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql (/opt/file:/opt/docspell-restserver-0.34.0/lib/com.github.eikek.docspell-store-0.34.0.jar!/db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql)
Line       : 37
Statement  : with
  missing_ids as (
    select file_id from filemeta
    except
    select file_id as file_id from valid_file_ids)
insert into obsolete_files (file_id)
  select file_id from filemeta
  where file_id in (select file_id from missing_ids)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:385)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:275)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:274)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$5(FlywayMigrate.scala:65)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:65)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$2(FlywayMigrate.scala:64)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:36)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:63)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at as @ docspell.restserver.RestServer$.$anonfun$serve$1(RestServer.scala:67)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.33.0__fix_reorganize_files.sql failed
--------------------------------------------------
SQL State  : 42703
Error Code : 0
Message    : ERROR: column "file_id" does not exist
  Position: 36
Location   : db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql (/opt/file:/opt/docspell-restserver-0.34.0/lib/com.github.eikek.docspell-store-0.34.0.jar!/db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql)
Line       : 37
Statement  : with
  missing_ids as (
    select file_id from filemeta
    except
    select file_id as file_id from valid_file_ids)
insert into obsolete_files (file_id)
  select file_id from filemeta
  where file_id in (select file_id from missing_ids)

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:69)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:58)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:377)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:275)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:274)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$5(FlywayMigrate.scala:65)
	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:591)
	at scala.concurrent.package$.blocking(package.scala:124)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:967)
	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
	at cats.effect.IOFiber.run(IOFiber.scala:140)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
Caused by: org.postgresql.util.PSQLException: ERROR: column "file_id" does not exist
  Position: 36
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)

	... 27 more
```

Could anyone help me migrating this successfully?

Thanks a lot!

**Comment by Madnex** [comment]
Thanks a lot!! This workaround did the trick :) Great tool btw, keep up the good work 👍 🎉
