### ISSUE TITLE
E-Mail Input: cannot select email from suggestion list

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#1565]
There is an error when adding a new notification channel (for email) by selecting the corresponding entry in the dropdown _as soon as it is shown by typing the name_ in the Recipient(s) field.
You **must** type the whole correct email address in the field and _then_ select the corresponding entry.

Otherwise I'm getting the error "_There was an invalid response status: 500._"

I start typing the email address and as soon as it is shown in the dropdown I select it:
![Bildschirmfoto vom 2022-05-22 19-47-54](https://user-images.githubusercontent.com/36138919/169708671-4f82ec69-db0f-4768-97a0-0da37bb64f79.png)

This is the result:
![2022-05-22 19 43 00 docspell flobine de d16a140e620a](https://user-images.githubusercontent.com/36138919/169708547-595ac637-7bc4-4a2e-9feb-a081aa913677.png)

This is the interresting part of the restserver docker log:

```
2022.05.22 19:41:43:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v1/sec/notification/channel
2022.05.22 19:41:43:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - service raised an error: class java.lang.IllegalArgumentException
2022.05.22 19:41:43:0000 [io-comp...] [ERROR] org.http4s.server.service-errors - Error servicing request: POST /api/v1/sec/notification/channel from 192.168.15.1
java.lang.IllegalArgumentException: Invalid mail address 'flo' - Missing final '@domain'
        at docspell.restapi.model.NotificationChannel$.$anonfun$convert$6(NotificationChannel.scala:75)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:172)
        at docspell.restapi.model.NotificationChannel$.$anonfun$convert$1(NotificationChannel.scala:75)
        at docspell.restapi.model.NotificationChannel$Mail.fold(NotificationChannel.scala:36)
        at docspell.restapi.model.NotificationChannel$.convert(NotificationChannel.scala:93)
        at docspell.restserver.routes.NotificationRoutes$$anonfun$channels$1.$anonfun$applyOrElse$4(NotificationRoutes.scala:67)
        at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
        at flatMap @ docspell.restserver.routes.NotificationRoutes$$anonfun$channels$1.$anonfun$applyOrElse$4(NotificationRoutes.scala:67)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
        at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:71)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
        at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1185)
        at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
```

It seems that not the clicked (whole) email address but the written word (beginning of the email address) is taken to store the data for a notification channel.
This explains the bug/error message "**Invalid mail address 'flo' - Missing final '@domain'**"

**Comment by eikek** [comment]
Thanks that is a ui bug (and the server should not give a 500 either…). Are you selecting via keyboard or mouse?

**Comment by vakilando** [comment]
with the mouse.
Just tried with keyboard and then it works...
