### ISSUE TITLE
Solr Error

### ISSUE THREAD

**Issue by DrAg0n141** [eikek/docspell#170]
Hi, i have installed all but Solr is not working. In Solr the logs show me this error. What i am doing wrong?

Thanks for the help.

org.apache.solr.common.SolrException: undefined field content
	at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1319)
	at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:462)
	at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:86)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:192)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:262)
	at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:527)
	at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)
	at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1102)
	at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:825)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:263)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
	at org.apache.solr.search.QParser.getQuery(QParser.java:174)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:302)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:211)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2596)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:802)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:579)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:420)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:352)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eikek** [comment]
Hm, I'm not sure. Did you use the docker setup? Or how did you install solr? This happens when you do a search from within docspell, right?

A guess: maybe the schema is not setup correctly. This should be done automatically when the joex component starts. This means, that the solr must be ready – the server must listen for connections, when joex starts. You can re-create everything using curl as described [here](https://docspell.org/doc/configure#full-text-search-solr). 

```
$ curl -XPOST http://localhost:7880/api/v1/open/fts/reIndexAll/test123
```
Where `test123` is the key that needs to be specified in the config file. Could you maybe try this? This should fix the schema and re-index all data, which could help.

**Comment by DrAg0n141** [comment]
I have installed it with the DEB Packages and Solr with that manual https://lucene.apache.org/solr/guide/8_4/installing-solr.html

**Comment by eikek** [comment]
Ok, thanks. I then assume that solr was not completely ready when docspell started up and so could not initialize it properly. On Debian you need to take care yourself that solr is ready when starting docspell. This can be tricky even with systemd, because the solr process may be up but the http interface not yet started.

However, this setup is only necessary to run once. So you can start solr, wait a few seconds (you can check in your browser by visting localhost:8983 as described in their docs), create a core and then start docspell or alternatively run the `curl` command from above. This creates the schema and indexes all data currently in your database. Once this is done, you can start them out of order next time, because solr is then only needed when a search is executed.

I guess, the docs could be extended in this regard….

**Comment by eikek** [comment]
Hi @DrAg0n141 did you resolve your issue? If so, I'd be interested in how the docs could be improved in this regard. Let me know, if you need help.

**Comment by DrAg0n141** [comment]
Hi, i have now installed the Docker Version and all is Working fine.

**Comment by eikek** [comment]
Thanks for the note! I then close this issue. Good it's working with docker at least :-)
