### ISSUE TITLE
Restserver docker image issues - NoSuchFieldError: EPOCH

### ISSUE THREAD

**Issue by jberggg** [eikek/docspell#1712]
As discussed in the docspell matrix channel the rest-server of my docspell installation crashes completely if I do certain item searches:

```
Aug 21 19:35:46 cargoship docspell-restserver[222584]: java.lang.NoSuchFieldError: EPOCH
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at docspell.store.queries.QItem$.$anonfun$findRelatedItems$2(QItem.scala:138)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]: java.lang.NoSuchFieldError: EPOCH
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at docspell.store.queries.QItem$.$anonfun$findRelatedItems$2(QItem.scala:138)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.free.Free.$anonfun$step$1(Free.scala:55)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.free.Free.step(Free.scala:56)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.free.Free.$anonfun$foldMap$1(Free.scala:143)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.data.KleisliFlatMap.$anonfun$tailRecM$2(Kleisli.scala:665)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:37)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.free.Free.$anonfun$step$1(Free.scala:55)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:36)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.IO$$anon$4.tailRecM(IO.scala:1498)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.StackSafeMonad.$anonfun$tailRecM$1(StackSafeMonad.scala:38)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.IOFiber.succeeded(IOFiber.scala:1185)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.IOFiber.runLoop(IOFiber.scala:268)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1393)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.IOFiber.run(IOFiber.scala:146)
Aug 21 19:35:46 cargoship podman-docspell-restserver-start[222442]:         at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:425)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.free.Free.step(Free.scala:56)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.free.Free.$anonfun$foldMap$1(Free.scala:143)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.data.KleisliFlatMap.$anonfun$tailRecM$2(Kleisli.scala:665)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:37)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:36)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.IO$$anon$4.tailRecM(IO.scala:1498)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.StackSafeMonad.$anonfun$tailRecM$1(StackSafeMonad.scala:38)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.IOFiber.succeeded(IOFiber.scala:1185)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.IOFiber.runLoop(IOFiber.scala:268)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1393)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.IOFiber.run(IOFiber.scala:146)
Aug 21 19:35:46 cargoship docspell-restserver[222584]:         at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:425)``` 

```

I run the `docspell/restserver:v0.38.0` image on ARM but same happens with `latest` tag.

@eikek  pointed out that this could be an incompatibility issue with jdk8. One would need to update the docker image to contain jdk11. This caused some troubles in the past according to @eikek that's why the images have jdk8 installed. I will give it a go but don't expect too much, I'm very low on time at the moment.

**Comment by eikek** [comment]
Thanks for reporting! The issue mentioned regarding problems related to the jdk is #1417. This problem here only applies to the arm64 docker images. The others use jdk11.
