### ISSUE TITLE
H2 Migration to 0.39.0 Fails

### ISSUE THREAD

**Issue by dkaparis** [eikek/docspell#1848]
I followed the instructions for H2 migration in the release info:

Used the `h2-util.sh` script to dump the database (with the default h2 version setting of 1.4.200), then in the dump manually changed the checksum in `flyway_schema_history` table as instructed, then restored to the same location with `H2_VERSION` set to 2.1.214.

After upgrading to 0.39.0, the rest server fails with the following output:

```
2022.11.16 19:07:48:0001 [io-comp...] [INFO ] docspell.restserver.RestServer.serve:50 - Starting server with options ServerOptions(Duration(45000ms),false,1024)
2022.11.16 19:07:53:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/fixups/h2, classpath:db/fixups/common)
2022.11.16 19:07:53:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:79 - !!! Running fixup migrations (repair=false)
2022.11.16 19:07:53:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 9.7.0 by Redgate
2022.11.16 19:07:53:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
2022.11.16 19:07:53:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - 
2022.11.16 19:07:53:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:h2:///srv/docspell/docspell.db (H2 2.1)
2022.11.16 19:07:53:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 2 migrations (execution time 00:00.076s)
2022.11.16 19:07:53:0007 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1.33.0
2022.11.16 19:07:53:0008 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
2022.11.16 19:07:53:0009 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/migration/h2, classpath:db/migration/common)
2022.11.16 19:07:53:0010 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runMain:59 - !!! Running main migrations (repair=false)
2022.11.16 19:07:53:0011 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:h2:///srv/docspell/docspell.db (H2 2.1)
2022.11.16 19:07:53:0012 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 68 migrations (execution time 00:00.289s)
2022.11.16 19:07:53:0013 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1.38.2
2022.11.16 19:07:54:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema "public" to version "1.39.0 - collective id"
2022.11.16 19:07:55:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema "public" to version "1.39.1 - file meta migration"
2022.11.16 19:08:12:0000 [io-comp...] [ERROR] org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate - Unable to rollback transaction
2022.11.16 19:08:12:0001 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema "public" to version "1.39.1 - file meta migration" failed! Please restore backups and roll back database and code!
2022.11.16 19:08:12:0002 [io-comp...] [ERROR] org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate - Unable to restore autocommit to original value for connection
2022.11.16 19:08:12:0003 [io-comp...] [ERROR] org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate - Unable to rollback transaction
2022.11.16 19:08:12:0004 [io-comp...] [ERROR] org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate - Unable to restore autocommit to original value for connection
2022.11.16 19:08:12:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.internal.exception.FlywaySqlException: Error while retrieving the list of applied migrations from Schema History table "public"."flyway_schema_history"
----------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 50000
Message    : General error: "org.h2.mvstore.MVStoreException: This store is closed [2.1.214/4]"; SQL statement:
SELECT "installed_rank","version","description","type","script","checksum","installed_on","installed_by","execution_time","success" FROM "public"."flyway_schema_history" WHERE "type" != 'TABLE' AND "installed_rank" > ? ORDER BY "installed_rank" [50000-214]

	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.refreshCache(JdbcTableSchemaHistory.java:227)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:191)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.calculateInstalledRank(SchemaHistory.java:210)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:291)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
	at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at liftF @ docspell.config.ConfigFactory$.$anonfun$checkSystemProperty$5(ConfigFactory.scala:100)
	at map @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
	at flatMap @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: This store is closed [2.1.214/4]"; SQL statement:
SELECT "installed_rank","version","description","type","script","checksum","installed_on","installed_by","execution_time","success" FROM "public"."flyway_schema_history" WHERE "type" != 'TABLE' AND "installed_rank" > ? ORDER BY "installed_rank" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.command.Command.executeQuery(Command.java:211)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.query(JdbcTemplate.java:340)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.refreshCache(JdbcTableSchemaHistory.java:200)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:191)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.calculateInstalledRank(SchemaHistory.java:210)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:291)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:591)
	at scala.concurrent.package$.blocking(package.scala:124)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:967)
	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
	at cats.effect.IOFiber.run(IOFiber.scala:140)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
Caused by: org.h2.mvstore.MVStoreException: This store is closed [2.1.214/4]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.checkOpen(MVStore.java:3087)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1381)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2566)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:633)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1125)
	at org.h2.mvstore.CursorPos.traverseDown(CursorPos.java:61)
	at org.h2.mvstore.Cursor.traverseDown(Cursor.java:169)
	at org.h2.mvstore.Cursor.<init>(Cursor.java:40)
	at org.h2.mvstore.MVMap.cursor(MVMap.java:731)
	at org.h2.mvstore.tx.TransactionMap$TMIterator.<init>(TransactionMap.java:1088)
	at org.h2.mvstore.tx.TransactionMap$CommittedIterator.<init>(TransactionMap.java:935)
	at org.h2.mvstore.tx.TransactionMap.chooseIterator(TransactionMap.java:852)
	at org.h2.mvstore.tx.TransactionMap.entryIterator(TransactionMap.java:836)
	at org.h2.mvstore.db.MVPrimaryIndex.find(MVPrimaryIndex.java:370)
	at org.h2.mvstore.db.MVPrimaryIndex.find(MVPrimaryIndex.java:232)
	at org.h2.mvstore.db.MVDelegateIndex.find(MVDelegateIndex.java:88)
	at org.h2.index.IndexCursor.find(IndexCursor.java:161)
	at org.h2.table.TableFilter.next(TableFilter.java:394)
	at org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1832)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:78)
	at org.h2.result.FetchedResult.next(FetchedResult.java:34)
	at org.h2.command.query.Select.queryFlat(Select.java:728)
	at org.h2.command.query.Select.queryWithoutCache(Select.java:833)
	at org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)
	at org.h2.command.query.Query.query(Query.java:512)
	at org.h2.command.query.Query.query(Query.java:475)
	at org.h2.command.CommandContainer.query(CommandContainer.java:251)
	at org.h2.command.Command.executeQuery(Command.java:190)
	... 26 more
Caused by: org.h2.mvstore.MVStoreException: java.lang.OutOfMemoryError: Capacity: 53747712 [2.1.214/3]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.serializeAndStore(MVStore.java:1605)
	at org.h2.mvstore.MVStore.lambda$storeNow$4(MVStore.java:1518)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Capacity: 53747712
	at org.h2.mvstore.WriteBuffer.grow(WriteBuffer.java:322)
	at org.h2.mvstore.WriteBuffer.ensureCapacity(WriteBuffer.java:302)
	at org.h2.mvstore.WriteBuffer.put(WriteBuffer.java:164)
	at org.h2.mvstore.db.ValueDataType.write(ValueDataType.java:393)
	at org.h2.mvstore.db.RowDataType.write(RowDataType.java:175)
	at org.h2.mvstore.db.RowDataType.write(RowDataType.java:29)
	at org.h2.mvstore.tx.VersionedValueType.write(VersionedValueType.java:116)
	at org.h2.mvstore.tx.VersionedValueType.write(VersionedValueType.java:100)
	at org.h2.mvstore.Page$Leaf.writeValues(Page.java:1609)
	at org.h2.mvstore.Page.write(Page.java:721)
	at org.h2.mvstore.Page$Leaf.writeUnsavedRecursive(Page.java:1618)
	at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344)
	at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330)
	at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344)
	at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330)
	at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344)
	at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330)
	at org.h2.mvstore.MVStore.serializeToBuffer(MVStore.java:1669)
	at org.h2.mvstore.MVStore.serializeAndStore(MVStore.java:1598)
	... 6 more
```

**Comment by eikek** [comment]
Hey, the trace says an out-of-memory error happened when a transaction was tried to roll back. Now I'm not sure if the error caused the rollback or whether the rollback caused the oom. Maybe try again with an increased heap size, the h2 db migrations can potentially be more memory expensive. Could also be that the migration 1.39.1 did not succeed. You can check the file here https://github.com/eikek/docspell/blob/master/modules/store/src/main/resources/db/migration/h2/V1.39.1__file_meta_migration.sql and you could try to apply it line by line.

**Comment by dkaparis** [comment]
It seems the migration process uses quite extensively both memory and disk space. After several attempts freeing up space I finally managed to run the migration successfully and now I'm running 0.39.0.

The converted database has also expanded quite a bit - my db file is now nearly 17 times larger than the original! Is that normal?

**Comment by dkaparis** [comment]
Before I noted the new database size, the system was completely bogged down due to the migration process and I had to reboot. Later, after starting docspell again, the db file had shrunk back a little smaller than the old file size and now the software seems to be working normally.

Probably was some still unfinished migration process stage.

Thanks for the hints.

**Comment by eikek** [comment]
It is likely that h2 does some cleanup on start (but probably not while running) to reduce disk space. I think this can be closed now. Otherwise just reopen
