### ISSUE TITLE
JOEX Container. DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12.

### ISSUE THREAD

**Issue by Vladimir-Va** [eikek/docspell#1887]
Hello Docspell team.
I try to setup Portainer stack from [docker-compose.yml](https://github.com/eikek/docspell/blob/master/docker/docker-compose/docker-compose.yml)
Can't start Stack yet
And joex container have log:
```
  Starting unoconv listener
/usr/local/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```
Is this the result of my stupidity or are the packages in the container outdated and therefore it does not start?

**Comment by eikek** [comment]
I think it is a mix - if you use the newest version of docspell it was build on the current (at the time) alpine. Unoconv is installed differently it may depend on older python packages. But this is a warning, it should start just fine. Are office documents not working for you (converting docx, odt into pdfs)? If it doesn't start at all, there should be other messages in the logs somewhere.

**Comment by Vladimir-Va** [comment]
Thank you I was able to run Portainer Stack on my synology NAS without warnings
but have cycle
```
***>  Config:   
***>  FileRepo: DefaultDatabase(true)
***>  
2022.12.19 14:44:09:0001 [io-comp...] [INFO ] docspell.restserver.RestServer.serve:50 - Starting server with options ServerOptions(Duration(45000ms),false,1024)
2022.12.19 14:44:14:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:86 - Fixup migrations not applied.
2022.12.19 14:44:14:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/migration/mariadb, classpath:db/migration/common)
2022.12.19 14:44:14:0002 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runMain:59 - !!! Running main migrations (repair=false)
2022.12.19 14:44:14:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 9.7.0 by Redgate
2022.12.19 14:44:14:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
2022.12.19 14:44:14:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - 
2022.12.19 14:44:14:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:mariadb://172.17.0.1:3307/docspell (MariaDB 10.3)
2022.12.19 14:44:16:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 1.26.3 (filestore).
Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:134)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
	at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at filter @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$3(FlywayMigrate.scala:76)
	at flatMap @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:74)
Dec 19, 2022 2:44:29 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2022.12.19 14:44:28:037 io-compute-blocker-2 INFO docspell.config.ConfigFactory.default:44
    Using config from environment variables!
2022.12.19 14:44:34:0000 [io-comp...] [INFO ] docspell.restserver.Main.run:34 - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.39.0 (#bd31ec2c)
***>  << REST Server >>
***>  Id:       rest1
***>  Base-Url: http://localhost:7880
***>  Database: jdbc:mariadb://172.17.0.1:3307/docspell
***>  Fts:      Solr(http://docspell-solr-1:8983/solr/docspell)
```
and
```
***>  
2022.12.19 14:51:45:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:86 - Fixup migrations not applied.
2022.12.19 14:51:45:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/migration/mariadb, classpath:db/migration/common)
2022.12.19 14:51:45:0002 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runMain:59 - !!! Running main migrations (repair=false)
2022.12.19 14:51:45:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 9.7.0 by Redgate
2022.12.19 14:51:45:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
2022.12.19 14:51:45:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - 
2022.12.19 14:51:45:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:mariadb://172.17.0.1:3307/docspell (MariaDB 10.3)
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 1.26.3 (filestore).
Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:134)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
	at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at filter @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$3(FlywayMigrate.scala:76)
	at flatMap @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at as @ docspell.joex.Main$.$anonfun$run$10(Main.scala:49)
Starting unoconv listener
/usr/local/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
Dec 19, 2022 2:52:02 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2022.12.19 14:52:01:259 io-compute-blocker-2 INFO docspell.config.ConfigFactory.default:44
    Using config from environment variables!
2022.12.19 14:52:07:0000 [io-comp...] [INFO ] docspell.joex.Main.run:37 - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.39.0 (#bd31ec2c)
***>  << JOEX >>
***>  Id:       joex1
***>  Base-Url: http://docspell-joex-1:7878
***>  Database: jdbc:mariadb://172.17.0.1:3307/docspell
***>  Fts:      Solr(http://docspell-solr-1:8983/solr/docspell)
***>  Config:   
***>  FileRepo: DefaultDatabase(true)
```
So far no idea what's going on.

**Comment by Vladimir-Va** [comment]
Portainer Stack work without errors
```
version: '3.8'
services:

  # The restserver and joex containers defined here are configured
  # using env variables. Both must connect to the same database and
  # solr instance. More information on configuring can be found here:
  # https://docspell.org/docs/configure
  #
  # Please replace the values of the following with a custom secret
  # string:
  #
  # - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
  # - DOCSPELL_SERVER_AUTH_SERVER__SECRET
  # - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE
  #   (use the same value at the consumedir container!)
  #
  # After creating an account, you may want to set signup mode to
  # "closed" or to "invite". When using invite, you must also set
  # DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD to some
  # secret.
  restserver:
    image: docspell/restserver:latest
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=TZ
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver-1:7880
      # Bcs docspell-restserver-1 is Portainer stack name convention
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=SECRET
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=SECRET
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=PWD
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:mariadb://172.17.0.1:3307/docspell
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=db_user
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr-1:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=HEADER__VALUE
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=PWD
      - DOCSPELL_SERVER_BACKEND_SIGNUP_INVITE__TIME=3 d
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
    depends_on:
      - solr
    #  - db

  joex:
    image: docspell/joex:latest
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    #   - -Djava.io.tmpdir=/path/to/othertemp
    restart: unless-stopped
    environment:
      - TZ=TZ
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex-1:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr-1:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=PWD
      - DOCSPELL_JOEX_JDBC_URL=jdbc:mariadb://172.17.0.1:3307/docspell
      - DOCSPELL_JOEX_JDBC_USER=db_user
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
    ports:
      - "7878:7878"
    depends_on:
      - solr
#      - db
    ## Uncomment when using the "docker" runner with addons
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /tmp:/tmp

  # The consumedir container watches a directory for files to upload
  # to docspell restserver. This uses the `dsc` tool. For information
  # on the available options, see `dsc --help`.
  # https://github.com/docspell/dsc
  #
  # The value after `Docspell-Integration` must match the secret
  # specified at the restserver via
  # DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE.
  #
  # The --not-matches "**/.*" option is to exclude hidden files.
  consumedir:
    image: docspell/dsc:latest
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver-1:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:HEADER__VALUE"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /volume1/docker/docspell/consumedir/docs:/opt/docs
    depends_on:
      - restserver
#  db:
#    image: postgres:15.1
#    container_name: doc-postgres
#    restart: unless-stopped
#    volumes:
#      - docspell-postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=docspell
#      - POSTGRES_PASSWORD=gD2_eGs[_@
#      - POSTGRES_DB=docspell

  solr:
    image: solr:9
    restart: unless-stopped
    volumes:
      - docspell-solr_data:/var/solr
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

volumes:
#  docspell-postgres_data:
  docspell-solr_data:
   external: true
```

**Comment by eikek** [comment]
Oh ok, taht shows the problem: it cannot apply teh database changes. Did you try an upgrade of Docspell? If so from which version to which?

The problem with MariaDB is, that it doesn't support transactions for statements that change/create tables. So that means you would need to check what teh problem was with the changset in question :/ 

The reboot-cycle is done by docker(compose), because it says `restart: unless-stopped` - so it restarts it all the time and docspell doesn't start up.

**Comment by Vladimir-Va** [comment]
After that if restart stack go to cycle restart
How to `Please remove any half-completed changes then run repair to fix the schema history.`
Where and how to find `any half-completed changes` and `run repair to fix the schema history`?

**Comment by eikek** [comment]
Aha, so the `You have an error in your SQL syntax…` is the root problem and the one before was after a subsequent startup attempt. It looks like your version of MariaDB is not supported. Which version of MariaDB do you use?

**Comment by Vladimir-Va** [comment]
Thank you for you support!
`jdbc:mariadb://172.17.0.1:3307/docspell (MariaDB 10.3)`

**Comment by eikek** [comment]
Yes, that is unfortunately not supported. You need at least 10.5.2 I think. It looks like the same problem as #1091

**Comment by Vladimir-Va** [comment]
Thanks for the help setip docker [PostgreSQL](https://www.postgresql.org/).
Docspell run fine!
Not clear for me:

1. If i need use public domain for docspell i need setup DOCSPELL_JOEX_BASE__URL=https://example.com:7878?
2. Сan't find `docspell.conf` as far as I understand, it should be created somewhere in the container with the recorded data from the `environment` compose file? I want to map it to a permanent directory on the disk, but I can't find this file in restserver/joex/consumedir/solr containers.
Or should I create a `docspell. conf` then to which containers and on which path it write:
```
volumes:
      - /volume1/docker/docspell/mydir:/???/???
```
Of course, I apologize for stupid questions, but for docker setup the topic is not clear for me.
I think this thread might help newbies in the future.

**Comment by eikek** [comment]
Glad it's working for you! I think if you can go with postgresql that is even better. To your questions:

1. You can set this optionally. If it is not set, the base-url is created from the request that reaches docspell. It is a bit safer to set it (only feasible if docspell is reachable through one domain only).
2. Please see this site for more details: https://docspell.org/docs/configure/main/ - You can use a config file or you can use environment variables. The provided docker compose file uses environment variables. But you can create and use a config file instead. Just mount it into the container and adapt the command to specify this new file. You can mount it to whatever path you want, because you need to specify it explicitly with the command. Something like this:
    ```
    volumes:
      - /host/docspell.conf:/opt/docspell.conf
    command:
      - /opt/docspell.conf
    ```
