### ISSUE TITLE
Migration issue with MariaDB 10.3.29 at first startup

### ISSUE THREAD

**Issue by zspalfi-dev** [eikek/docspell#1911]
I tried to use docspell (docspell-restserver-0.39.0) with MariaDB (10.3.29), but the initial start always fails in a migration step. It says the 
ALTER TABLE `filemeta`
RENAME COLUMN `id` TO `file_id`
command has syntax error. Please see the logs:

2023.01.06 02:49:24:085 io-compute-blocker-1 INFO docspell.config.ConfigFactory.default:36
    Using config file: /opt/docspell/docspell-server.conf
2023.01.06 02:49:27:354 io-compute-blocker-1 WARN docspell.restserver.ConfigFile.generateSecretIfEmpty:63
    No serverSecret specified. Generating a random one. It is recommended to add a server-secret in the config file.
2023.01.06 02:49:27:0000 [io-comp...] [INFO ] docspell.restserver.Main.run:34 -
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.39.0 (#bd31ec2c)
***>  << REST Server >>
***>  Id:       rest1
***>  Base-Url: http://localhost:7880
***>  Database: jdbc:mariadb://localhost:3306/Docspell
***>  Fts:      -
***>  Config:   /opt/docspell/docspell-server.conf
***>  FileRepo: FileSystem(true,/mnt/hdd/docspell)
***>
2023.01.06 02:49:27:0001 [io-comp...] [INFO ] docspell.restserver.RestServer.serve:50 - Starting server with options ServerOptions(Duration(45000ms),false,1024)
2023.01.06 02:49:30:0000 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1146-42S02: Table 'Docspell.flyway_schema_history' doesn't exist
2023.01.06 02:49:30:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/migration/mariadb, classpath:db/migration/common)
2023.01.06 02:49:30:0002 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runMain:59 - !!! Running main migrations (repair=false)
2023.01.06 02:49:30:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 9.7.0 by Redgate
2023.01.06 02:49:30:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
2023.01.06 02:49:30:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter -
2023.01.06 02:49:30:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:mariadb://localhost/Docspell (MariaDB 10.3)
2023.01.06 02:49:30:0007 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 71 migrations (execution time 00:00.333s)
2023.01.06 02:49:30:0008 [io-comp...] [INFO ] org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table `Docspell`.`flyway_schema_history` ...
2023.01.06 02:49:31:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema `Docspell`: << Empty Schema >>
2023.01.06 02:49:31:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.0.0 - initial database"
2023.01.06 02:49:38:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.1.0 - useremail"
2023.01.06 02:49:38:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.2.0 - origin source"
2023.01.06 02:49:39:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.3.0 - periodic job"
2023.01.06 02:49:39:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.4.0 - attachment archive"
2023.01.06 02:49:41:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.5.0 - userimap"
2023.01.06 02:49:41:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.6.0 - integration enabled"
2023.01.06 02:49:42:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.6.1 - fix timestamp columns"
2023.01.06 02:49:45:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.7.0 - fts-migration"
2023.01.06 02:49:45:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.7.1 - fix item date"
2023.01.06 02:49:48:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.8.0 - folders"
2023.01.06 02:49:51:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.9.0 - updated column"
2023.01.06 02:49:52:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.9.1 - classifier"
2023.01.06 02:49:52:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.9.2 - fix text length"
2023.01.06 02:49:56:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.9.3 - joblog counter"
2023.01.06 02:49:56:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.9.4 - unique equipments"
2023.01.06 02:49:56:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.10.0 - attachment preview"
2023.01.06 02:49:58:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.11.0 - pdf pages"
2023.01.06 02:49:58:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.12.0 - upload data"
2023.01.06 02:49:58:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.13.0 - custom fields"
2023.01.06 02:49:59:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.14.0 - person org"
2023.01.06 02:50:00:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.15.0 - rememberme"
2023.01.06 02:50:00:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.16.0 - add imap oauth"
2023.01.06 02:50:01:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.17.0 - meta language"
2023.01.06 02:50:01:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.18.0 - classifier model"
2023.01.06 02:50:04:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.19.0 - add classify meta"
2023.01.06 02:50:04:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.19.1 - remove enabled"
2023.01.06 02:50:04:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.20.0 - personuse"
2023.01.06 02:50:06:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.20.1 - equipment description"
2023.01.06 02:50:06:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.20.2 - org shortname"
2023.01.06 02:50:06:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.20.3 - node seen"
2023.01.06 02:50:06:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.20.4 - source lang"
2023.01.06 02:50:06:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.21.0 - cast function"
2023.01.06 02:50:06:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.21.1 - equip org use"
2023.01.06 02:50:08:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.22.0 - add task name"
2023.01.06 02:50:08:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.23.0 - clientsettings"
2023.01.06 02:50:08:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.24.0 - drop fts migration"
2023.01.06 02:50:08:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.25.0 - add empty trash"
2023.01.06 02:50:09:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.25.1 - fix periodic submitter value"
2023.01.06 02:50:09:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.25.2 - add trash min age"
2023.01.06 02:50:09:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.25.3 - delete corrupt trash task"
2023.01.06 02:50:09:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.25.4 - add source attachonly"
2023.01.06 02:50:11:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.26.0 - missing indexes"
2023.01.06 02:50:11:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.26.1 - totp"
2023.01.06 02:50:11:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.26.2 - openid"
2023.01.06 02:50:12:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `Docspell` to version "1.26.3 - filestore"
2023.01.06 02:50:13:0000 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your                            MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
2023.01.06 02:50:13:0001 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema `Docspell` to version "1.26.3 - filestore" failed! Please restore backups and                            roll back database and code!
2023.01.06 02:50:13:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 clo                           sed=false
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.26.3__filestore.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=247394) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`'                            at line 2
Location   : db/migration/mariadb/V1.26.3__filestore.sql (/home/zspalfi/file:/opt/docspell/docspell-restserver-0.39.0/lib/com.github.eikek.docspell-store-0.39.0.jar!/db/migration/mariadb/V1.                           26.3__filestore.sql)
Line       : 4
Statement  : ALTER TABLE `filemeta`
RENAME COLUMN `id` TO `file_id`

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
        at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
        at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
        at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
        at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:74)
        at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3680)
        at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3680)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.26.3__filestore.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=247394) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`'                            at line 2
Location   : db/migration/mariadb/V1.26.3__filestore.sql (/home/zspalfi/file:/opt/docspell/docspell-restserver-0.39.0/lib/com.github.eikek.docspell-store-0.39.0.jar!/db/migration/mariadb/V1.                           26.3__filestore.sql)
Line       : 4
Statement  : ALTER TABLE `filemeta`
RENAME COLUMN `id` TO `file_id`

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
        at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
        at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
        at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:591)
        at scala.concurrent.package$.blocking(package.scala:124)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:967)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
        at cats.effect.IOFiber.run(IOFiber.scala:140)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
Caused by: java.sql.SQLSyntaxErrorException: (conn=247394) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use                            near 'COLUMN `id` TO `file_id`' at line 2
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:840)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:779)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:698)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:641)
        at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
        at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
        at org.mariadb.jdbc.Statement.execute(Statement.java:452)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
        ... 26 more

**Comment by eikek** [comment]
Yes, unfortunately MariaDB from 10.5.2 is supported, but 10.3 is not. For reference see #1091
