### ISSUE TITLE
Install fail - flyway/mariadb incompatibility?

### ISSUE THREAD

**Issue by KeithB** [eikek/docspell#2028]
Hi!

I'm trying to get docspell up and running from a docker compose install using a standalone MariaDB instance (10.6) - docker-compose has come from the docspell github and amended to point to the standalone DB and not spin up the postgres database. I've tried a couple of different docspell versions (0.40 and 0.39) but get the same errors related to a flyway cast migration

```
2023.04.03 09:07:57:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.21.0__cast_function.sql failed
-------------------------------------------
SQL State  : HY000
Error Code : 1419
Message    : (conn=118285) You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
Location   : db/migration/mariadb/V1.21.0__cast_function.sql (/opt/file:/opt/docspell-restserver-0.39.0/lib/com.github.eikek.docspell-store-0.39.0.jar!/db/migration/mariadb/V1.21.0__cast_function.sql)
Line       : 3
Statement  : -- Create a function to cast to a numeric, if an error occurs return null
-- Could not get it working with decimal type, so using double
create or replace function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(s as double)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
	at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at filter @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$3(FlywayMigrate.scala:76)
	at flatMap @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:74)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.21.0__cast_function.sql failed
```

then
```
2023.04.02 20:15:21:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 1.21.0 (cast function).

```
Setting up the database in MariaDB, the docspell user is given full access to the docspell database (`ALL ON docspell.*`)

I haven't been able to find anything either through docspell or flyway/MariaDB as to what would cause it yet. Is there some gotcha I've missed?

Thank you!

**Comment by eikek** [comment]
Not sure really, the message `You do not have the SUPER privilege` indicates that the user misses some privileges to create the function in your setup. IIUC you need to disable binary logging as suggested in the message or give the user SUPER privileges

**Comment by KeithB** [comment]
Thanks for the quick response @eikek - much appreciated.

Must admit, I hadn't expected something privileges related given the app had been given full access to it's DB but you're right. The particular migration item that caused the issue creates a new function which in turn tripped over the binary logging config. (For others that might see this later there's a good explanation of the reason for the security constraint [here](https://stackoverflow.com/questions/56389698/why-super-privileges-are-disabled-when-binary-logging-option-is-on).)

At some point I'll take a look at removing binary logging (it's a standalone DB without replication) but given there's other stuff running against this DB, for now I've gone down the route of enabled `log_bin_trust_function_creators` seeing as the security risk it protects against doesn't apply in my setup.

Looking forward to experimenting with docspell now!

**Comment by eikek** [comment]
You're welcome! And great to hear it's working. I'm not very familiar with MariaDB so couldn't help really. I didn't see this when I was testing with my local mariadb test-installation.

**Comment by KeithB** [comment]
Closing - docspell is working as outlined above.
