### ISSUE TITLE
1.21.0 - cast function SQL Syntax Error

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [eikek/docspell#2037]
I'm running a fresh install of docspell wih the mysql (mariadb) backend.
I receive the following error on setting up / migrating the database:

```
2023.04.10 23:24:01:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell` to version "1.21.0 - cast function"
2023.04.10 23:24:01:0005 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(' at line 3
2023.04.10 23:24:01:0006 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema `docspell` to version "1.21.0 - cast function" failed! Please restore backups and roll back database and code!
2023.04.10 23:24:01:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.21.0__cast_function.sql failed
-------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=4871) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(' at line 3
Location   : db/migration/mariadb/V1.21.0__cast_function.sql (/home/docspell/docspell-restserver-0.40.0/file:/home/docspell/docspell-restserver-0.40.0/lib/com.github.eikek.docspell-store-0.40.0.jar!/db/migration/mariadb/V1.21.0__cast_function.sql)
Line       : 3
Statement  : -- Create a function to cast to a numeric, if an error occurs return null
-- Could not get it working with decimal type, so using double
create or replace function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(s as double)

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
        at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:177)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:196)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:129)
        at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
        at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
        at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
        at filter @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$3(FlywayMigrate.scala:76)
        at flatMap @ docspell.config.ConfigFactory$.checkSystemProperty(ConfigFactory.scala:94)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.21.0__cast_function.sql failed
-------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=4871) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(' at line 3
Location   : db/migration/mariadb/V1.21.0__cast_function.sql (/home/docspell/docspell-restserver-0.40.0/file:/home/docspell/docspell-restserver-0.40.0/lib/com.github.eikek.docspell-store-0.40.0.jar!/db/migration/mariadb/V1.21.0__cast_function.sql)
Line       : 3
Statement  : -- Create a function to cast to a numeric, if an error occurs return null
-- Could not get it working with decimal type, so using double
create or replace function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(s as double)

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
        at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:177)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:196)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:129)
        at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
        at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:631)
        at scala.concurrent.package$.blocking(package.scala:124)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:958)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1330)
        at cats.effect.IOFiber.run(IOFiber.scala:119)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:555)
Caused by: java.sql.SQLSyntaxErrorException: (conn=4871) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(' at line 3
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:855)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:794)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:713)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:637)
        at org.mariadb.jdbc.Statement.executeInternal(Statement.java:941)
        at org.mariadb.jdbc.Statement.execute(Statement.java:1067)
        at org.mariadb.jdbc.Statement.execute(Statement.java:458)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
        ... 26 more
```

**Comment by Unkn0wn-MDCLXIV** [comment]
Just noticed another issue stating that mysql is not supported.
