### ISSUE TITLE
[deb] `make-deb` fails with umask 007

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2370]
If umask is 007 (instead of 022), then the `make-deb` build fails with:

```
[error] dpkg-deb: error: control directory has bad permissions 770 (must be >=0755 and <=0775)
```

I think that the build process should set permissions explicitly rather than rely on the correct umask set.

**Comment by madduck** [comment]
Hint: to recover, you need to `chmod 755 ./modules/restserver/target/docspell-restserver-0.41.0-SNAPSHOT/DEBIAN`

**Comment by eikek** [comment]
I'm not sure if I understand: where is this being called? Is this part of the plugin that does the debian build - and this fails now?

**Comment by madduck** [comment]
Nothing is being called anywhere. I have `umask 007` in my shell, so new directories get permissions 0770 by default. When `sbt` builds the Debian package, it creates `./modules/restserver/target/docspell-restserver-0.41.0-SNAPSHOT/DEBIAN` at some point, but **does not explicitly set the permissions** of that directory.

Later, it, or the Scala Debian tools, or Debian itself, fails, because the directory does not have the proper permissions.

This bug is probably only exposed just now because most people just use the default umask of 022. But my argument is that if something requires a certain permission in the build process, it needs to set that permission, and not rely on the default.

**Comment by madduck** [comment]
to reproduce:

1. rm -r modules/restserver/target/docspell-restserver-0.41.0-SNAPSHOT/DEBIAN
2. umask 007
3. sbt make-deb

this should yield:

```
[info] welcome to sbt 1.9.7 (Debian Java 17.0.9)
[info] loading settings for project docspell-build from build.sbt,plugins.sbt ...
[info] loading project definition from /home/madduck/code/docspell/project
[info] loading settings for project root from build.sbt,version.sbt ...
[info] resolving key references (37293 settings) ...
[info] set current project to docspell-root (in build file:/home/madduck/code/docspell/)
[info] Copy webjar resources from 1 files/directories.
[info] Wrote /home/madduck/code/docspell/modules/restserver/target/scala-2.13/docspell-restserver_2.13-0.41.0-SNAPSHOT.pom
[info] Copy webjar resources from 1 files/directories.
[info] Compiling css stylesheets…
[info] Running npx postcss /home/madduck/code/docspell/modules/webapp/src/main/styles/index.css -o /home/madduck/code/docspell/modules/webapp/target/scala-2.13/resource_managed/main/META-INF/resources/webjars/docspell-webapp/0.41.0-SNAPSHOT/css/styles.css --env development
[info] Compile elm files ...
[info] Running elm make --debug --output /home/madduck/code/docspell/modules/webapp/target/scala-2.13/resource_managed/main/META-INF/resources/webjars/docspell-webapp/0.41.0-SNAPSHOT/docspell-app.js /home/madduck/code/docspell/modules/webapp/src/main/elm/Main.elm
[info] Compiling ...
[info]              
[info] Success!
[info] 
[info]     Main ───> /home/madduck/code/docspell/modules/webapp/target/scala-2.13/resource_managed/main/META-INF/resources/webjars/docspell-webapp/0.41.0-SNAPSHOT/docspell-app.js
[info] Produced query js file: /home/madduck/code/docspell/modules/query/js/target/scala-2.13/docspell-query-opt.js
[info] Copy webjar resources from 1 files/directories.
[error] 
[error] warn - The `@variants` directive has been deprecated in Tailwind CSS v3.0.
[error] warn - Use `@layer utilities` or `@layer components` instead.
[error] warn - https://tailwindcss.com/docs/upgrade-guide#replace-variants-with-layer
[info] Styles built at /home/madduck/code/docspell/modules/webapp/target/scala-2.13/resource_managed/main/META-INF/resources/webjars/docspell-webapp/0.41.0-SNAPSHOT
[info] Main Scala API documentation to /home/madduck/code/docspell/modules/restserver/target/scala-2.13/api...
[info] compiling 1 Scala source to /home/madduck/code/docspell/modules/restserver/target/scala-2.13/classes ...
[info] Main Scala API documentation successful.
[info] Wrote /home/madduck/code/docspell/modules/logging/api/target/scala-2.13/docspell-logging-api_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/logging/scribe/target/scala-2.13/docspell-logging-scribe_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/common/target/scala-2.13/docspell-common_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/fts-client/target/scala-2.13/docspell-fts-client_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/files/target/scala-2.13/docspell-files_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/addonlib/target/scala-2.13/addonlib_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/query/jvm/target/scala-2.13/docspell-query_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/totp/target/scala-2.13/docspell-totp_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/notification/api/target/scala-2.13/docspell-notification-api_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/jsonminiq/target/scala-2.13/docspell-jsonminiq_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/store/target/scala-2.13/docspell-store_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/fts-psql/target/scala-2.13/docspell-fts-psql_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/config/target/scala-2.13/docspell-config_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/restapi/target/scala-2.13/docspell-restapi_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/joexapi/target/scala-2.13/docspell-joexapi_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/pubsub/api/target/scala-2.13/docspell-pubsub-api_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/scheduler/api/target/scala-2.13/docspell-scheduler-api_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/backend/target/scala-2.13/docspell-backend_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/query/js/target/scala-2.13/docspell-query_sjs1_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/webapp/target/scala-2.13/docspell-webapp_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/fts-solr/target/scala-2.13/docspell-fts-solr_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/oidc/target/scala-2.13/docspell-oidc_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/pubsub/naive/target/scala-2.13/docspell-pubsub-naive_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/notification/impl/target/scala-2.13/docspell-notification-impl_2.13-0.41.0-SNAPSHOT.pom
[info] Wrote /home/madduck/code/docspell/modules/scheduler/impl/target/scala-2.13/docspell-scheduler-impl_2.13-0.41.0-SNAPSHOT.pom
[info] Building debian package with native implementation
[error] dpkg-deb: error: control directory has bad permissions 770 (must be >=0755 and <=0775)
[error] java.lang.RuntimeException: Failure packaging debian file.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.typesafe.sbt.packager.debian.DebianNativePackaging.buildPackage(DebianNativePackaging.scala:118)
[error] 	at com.typesafe.sbt.packager.debian.DebianNativePackaging.$anonfun$debianNativeSettings$5(DebianNativePackaging.scala:69)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (restserver / Debian / packageBin) Failure packaging debian file.  Exit code: 2
```

```

**Comment by eikek** [comment]
Ah ok, so it's only when creating the deb package. Well, tbh I don't care :) They are build on the ci and this is working. It wuold be a problem if installing fails. Anyways, I think this needs to be addressed at the [sbt-native-packager plugin](https://github.com/sbt/sbt-native-packager/).

**Comment by madduck** [comment]
I'll take it there, thanks.

**Comment by madduck** [comment]
Already there: https://github.com/sbt/sbt-native-packager/issues/829
