### ISSUE TITLE
Migration of schema `docspell_db` to version "1.26.3 - filestore" failed!

### ISSUE THREAD

**Issue by JacTra** [eikek/docspell#2481]
Hi,

OK, I admit, don't know what to do! :-| I've been trying to install dockerized Doscpell on Raspberry Pi 5 and... it does not work. I tried both with filesystem (mounted folder) and with my MariaDB options (my database is on Synology NAS). And everytime it breaks with migration / syntax exception error. 

Log file and docker compose copied below.

What am I doing wrong / missing here...? :(

Jacek

--- Log ---
```
2024.01.31 18:24:11:500 io-compute-blocker-2 INFO docspell.config.ConfigFactory.default:47
    Using config from environment variables!    
2024.01.31 18:24:14:0000 [io-comp...] [INFO ] docspell.restserver.Main.run:34 - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.41.0 (#50dadad4)
***>  << REST Server >>
***>  Id:       rest1
***>  Base-Url: http://localhost:7880
***>  Database: jdbc:mariadb://192.168.1.235:3307/docspell_db
***>  Fts:      Solr(http://docspell-solr:8983/solr/docspell)
***>  Config:   
***>  FileRepo: DefaultDatabase(true)
***>  
2024.01.31 18:24:14:0001 [io-comp...] [INFO ] docspell.restserver.RestServer.serve:52 - Starting server with options ServerOptions(Duration(45000ms),false,16)
2024.01.31 18:24:17:0000 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1146-42S02: Table 'docspell_db.flyway_schema_history' doesn't exist
2024.01.31 18:24:17:0001 [io-comp...] [ERROR] docspell.store.impl.DoobieLogging.run:30 - SQL exec failed: select count(1) from flyway_schema_history (List())
java.sql.SQLSyntaxErrorException: (conn=5930) Table 'docspell_db.flyway_schema_history' doesn't exist
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:172)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:913)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:852)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:771)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:695)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
	at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:296)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:907)
	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:107)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
	at uncancelable @ doobie.WeakAsync$$anon$1.uncancelable(WeakAsync.scala:37)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
	at suspend @ doobie.WeakAsync$$anon$1.suspend(WeakAsync.scala:35)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
2024.01.31 18:24:17:0002 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:34 - Creating Flyway for: List(classpath:db/migration/mariadb, classpath:db/migration/common)
2024.01.31 18:24:19:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runMain:59 - !!! Running main migrations (repair=true)
2024.01.31 18:24:19:0001 [io-comp...] [INFO ] org.flywaydb.core.FlywayExecutor - Database: jdbc:mariadb://192.168.1.235:3307/docspell_db (MariaDB 10.3)
2024.01.31 18:24:19:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Repair of failed migration in Schema History table `docspell_db`.`flyway_schema_history` not necessary. No failed migration detected.
2024.01.31 18:24:19:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbRepair - Successfully repaired schema history table `docspell_db`.`flyway_schema_history` (execution time 00:00.405s).
2024.01.31 18:24:20:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 71 migrations (execution time 00:00.236s)
2024.01.31 18:24:20:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema `docspell_db`: 1.0.0
2024.01.31 18:24:20:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.1.0 - useremail"
2024.01.31 18:24:22:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.3.0 - periodic job"
2024.01.31 18:24:22:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.5.0 - userimap"
2024.01.31 18:24:22:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.6.1 - fix timestamp columns"
2024.01.31 18:24:25:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.7.1 - fix item date"
2024.01.31 18:24:26:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.9.0 - updated column"
2024.01.31 18:24:26:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.9.2 - fix text length"
2024.01.31 18:24:28:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.9.4 - unique equipments"
2024.01.31 18:24:28:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.11.0 - pdf pages"
2024.01.31 18:24:28:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.13.0 - custom fields"
2024.01.31 18:24:28:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.15.0 - rememberme"
2024.01.31 18:24:30:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.17.0 - meta language"
2024.01.31 18:24:30:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.19.0 - add classify meta"
2024.01.31 18:24:31:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.20.0 - personuse"
2024.01.31 18:24:31:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.20.2 - org shortname"
2024.01.31 18:24:31:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.20.4 - source lang"
2024.01.31 18:24:31:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.21.1 - equip org use"
2024.01.31 18:24:32:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.23.0 - clientsettings"
2024.01.31 18:24:32:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.25.0 - add empty trash"
2024.01.31 18:24:32:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.25.2 - add trash min age"
2024.01.31 18:24:34:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.25.4 - add source attachonly"
2024.01.31 18:24:34:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.26.1 - totp"
2024.01.31 18:24:35:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `docspell_db` to version "1.26.3 - filestore"
2024.01.31 18:24:35:0001 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
2024.01.31 18:24:35:0002 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema `docspell_db` to version "1.26.3 - filestore" failed! Please restore backups and roll back database and code!
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.26.3__filestore.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=5942) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Location   : db/migration/mariadb/V1.26.3__filestore.sql (/opt/file:/opt/docspell-restserver-0.41.0/lib/com.github.eikek.docspell-store-0.41.0.jar!/db/migration/mariadb/V1.26.3__filestore.sql)
Line       : 4
Statement  : ALTER TABLE `filemeta`
RENAME COLUMN `id` TO `file_id`
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:382)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:150)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:203)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$6(FlywayMigrate.scala:61)
	at void @ org.typelevel.keypool.KeyPool$.reap(KeyPool.scala:187)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$4(FlywayMigrate.scala:60)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runMain$2(FlywayMigrate.scala:59)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:29)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:34)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:33)
	at flatMap @ docspell.store.migrate.FlywayMigrate.runMain(FlywayMigrate.scala:58)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:48)
	at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:75)
	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:165)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.26.3__filestore.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=5942) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
Location   : db/migration/mariadb/V1.26.3__filestore.sql (/opt/file:/opt/docspell-restserver-0.41.0/lib/com.github.eikek.docspell-store-0.41.0.jar!/db/migration/mariadb/V1.26.3__filestore.sql)
Line       : 4
Statement  : ALTER TABLE `filemeta`
RENAME COLUMN `id` TO `file_id`
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:272)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:227)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:130)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:150)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:203)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runMain$7(FlywayMigrate.scala:61)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:1004)
	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1372)
	at cats.effect.IOFiber.run(IOFiber.scala:113)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:702)
Caused by: java.sql.SQLSyntaxErrorException: (conn=5942) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:172)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:913)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:852)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:771)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:695)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:1035)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1165)
	at org.mariadb.jdbc.Statement.execute(Statement.java:493)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:89)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:215)
      
	... 24 more
2024.01.31 18:24:40:732 io-compute-blocker-2 INFO docspell.config.ConfigFactory.default:47
```
--- Docker compose (redacted) ---
```
version: '3.8'
services:

  # The restserver and joex containers defined here are configured
  # using env variables. Both must connect to the same database and
  # solr instance. More information on configuring can be found here:
  # https://docspell.org/docs/configure
  #
  # Please replace the values of the following with a custom secret
  # string:
  #
  # - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
  # - DOCSPELL_SERVER_AUTH_SERVER__SECRET
  # - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE
  #   (use the same value at the consumedir container!)
  #
  # After creating an account, you may want to set signup mode to
  # "closed" or to "invite". When using invite, you must also set
  # DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD to some
  # secret.
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_BACKEND_DATABASE__SCHEMA_REPAIR__SCHEMA=true
      #- SPRING_FLYWAY_BASELINEONMIGRATE=true
      #- SPRING_FLYWAY_BASELINE__VERSION=0
      - SPRING_FLYWAY_CLEAN__ON__VALIDATION__ERROR=true
      - SPRING_FLYWAY_CLEAN__DISABLED=false
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=VerySecret
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=VerySecret
      #- DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=filesystem
      #- DOCSPELL_SERVER_BACKEND_FILES_STORES_DATABASE_ENABLED=false
      #- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_DIRECTORY=/mnt/remote_doclibrary/docspell
      #- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_ENABLED=true
      #- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_TYPE=file-system
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=VerySecret
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:mariadb://192.168.1.x:3307/docspell_db
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=VerySecret
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=VerySecret
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_SOURCE__NAME=RPi5
      - DOCSPELL_SERVER_SERVER__OPTIONS_MAX__CONNECTIONS=16
    depends_on:
      - solr

  joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=VerySecret
      - DOCSPELL_JOEX_JDBC_URL=jdbc:mariadb://192.168.1.x:3307/docspell_db
      - DOCSPELL_JOEX_JDBC_USER=VerySecret
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
    ports:
      - "7878:7878"
    depends_on:
      - solr
      
    ## Uncomment when using the "docker" runner with addons
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # The consumedir container watches a directory for files to upload
  # to docspell restserver. This uses the `dsc` tool. For information
  # on the available options, see `dsc --help`.
  # https://github.com/docspell/dsc
  #
  # The value after `Docspell-Integration` must match the secret
  # specified at the restserver via
  # DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE.
  #
  # The --not-matches "**/.*" option is to exclude hidden files.
  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:VerySecret"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - ./docs:/opt/docs
    depends_on:
      - restserver
 
  solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - docspell-solr_data:/var/solr
    command:
      - bash
      - -c
      - 'precreate-core docspell; exec solr -f -Dsolr.modules=analysis-extras'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

volumes:
    docspell-solr_data:
```

**Comment by eikek** [comment]
Hi @JacTra I edited your message to add code blocks, otherwise it is really hard to read :) 

I think the problem is a too old maria db version. Which version do you use? You need >10.6, older ones don't support this `RENAME TO` syntax.

**Comment by JacTra** [comment]
Thank you for format edits (wasn't sure how to do that) - really appreciate it!

Just checked and apparently... you're right! On my ~5 years old NAS Synology updated MariaDB to 10.3.32 only and won't update it anymore. :-O So, I guess I need to install the newest instance via Docker, if I want to utilize this NAS storage.

Thank you for such a prompt reply!

**Comment by eikek** [comment]
You're welcome! If you need to run something extra anyways, maybe consider postgresql. Docspell is more tested with postgres than mariadb. But, of course, mariadb should be fine as well.

**Comment by JacTra** [comment]
I went with MariaDB on Docker since I will eventually migrate there a couple of other databases from the older instance. Everything works like a charm! :) Thank you!
