### ISSUE TITLE
[Bug] Solr full-text search broken: 'Client exception => org.apache.solr.common.SolrException: undefined field content_sk'

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#2495]
Hello there

I'm recently running into the problem, that I cannot use the full-text search. After digging a bit through the logs, I disovered this in the Solr logs:

```log
docspell-solr  | 2024-02-14 19:52:49.921 ERROR (qtp1415289182-17-null-14) [c: s: r: x:docspell t:null-14] o.a.s.h.RequestHandlerBase Client exception => org.apache.solr.common.SolrException: undefined field content_sk
docspell-solr  |        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1485)
docspell-solr  | org.apache.solr.common.SolrException: undefined field content_sk
docspell-solr  |        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1485) ~[?:?]
docspell-solr  |        at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:506) ~[?:?]
docspell-solr  |        at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:83) ~[?:?]
docspell-solr  |        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:184) ~[?:?]
docspell-solr  |        at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:257) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:530) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:68) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1143) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:859) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Term(QueryParser.java:454) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:293) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:173) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:298) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:235) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:143) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:276) ~[?:?]
docspell-solr  |        at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:51) ~[?:?]
docspell-solr  |        at org.apache.solr.search.QParser.getQuery(QParser.java:188) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:173) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:431) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:226) ~[?:?]
docspell-solr  |        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2884) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.HttpSolrCall.executeCoreRequest(HttpSolrCall.java:875) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:561) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:262) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:219) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:249) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:215) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:213) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195) ~[?:?]
docspell-solr  |        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598) ~[jetty-security-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:228) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301) ~[jetty-rewrite-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
docspell-solr  | 2024-02-14 19:52:49.921 ERROR (qtp1415289182-23-null-13) [c: s: r: x:docspell t:null-13] o.a.s.h.RequestHandlerBase Client exception => org.apache.solr.common.SolrException: undefined field content_sk
docspell-solr  |        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1485)
docspell-solr  | org.apache.solr.common.SolrException: undefined field content_sk
docspell-solr  |        at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1485) ~[?:?]
docspell-solr  |        at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:506) ~[?:?]
docspell-solr  |        at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:83) ~[?:?]
docspell-solr  |        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:184) ~[?:?]
docspell-solr  |        at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:257) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:530) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:68) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1143) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:859) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Term(QueryParser.java:454) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:293) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:173) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:298) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.Query(QueryParser.java:235) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:143) ~[?:?]
docspell-solr  |        at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:276) ~[?:?]
docspell-solr  |        at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:51) ~[?:?]
docspell-solr  |        at org.apache.solr.search.QParser.getQuery(QParser.java:188) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:173) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:431) ~[?:?]
docspell-solr  |        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:226) ~[?:?]
docspell-solr  |        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2884) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.HttpSolrCall.executeCoreRequest(HttpSolrCall.java:875) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:561) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:262) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:219) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:249) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:215) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:213) ~[?:?]
docspell-solr  |        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195) ~[?:?]
docspell-solr  |        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598) ~[jetty-security-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:228) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301) ~[jetty-rewrite-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) ~[jetty-server-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[jetty-util-10.0.19.jar:10.0.19]
docspell-solr  |        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

Going further and getting the list of fields (the entire schema) inside solr with:
```bash
$ curl http://localhost:8983/solr/docspell/schema/fields
```

It doesn't list anything with `content_sk`, so that seems to be the problem.

Is something missing when creating the index, which is later requested?
Seems a full index *is* created, but some fields are missing.

**Comment by TheAnachronism** [comment]
Turns out, I'm just an idiot, who forgot to update joex, when updating the rest…
With everything running on `v0.41.0` and joex still on `v.40.0`, things have to go wrong at some point….

After updating everything properly to `v0.41.0` search works again.

**Comment by eikek** [comment]
Nice, glad it is working again. 👍🏼 Indeed, joex is migrating the solr index.
