### ISSUE TITLE
Joex crash java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Lucki** [eikek/docspell#284]
Since speed isn't important and your documentation already has the rPi [mentioned](https://docspell.org/docs/install/rpi/) I gave this a try on a similar device.
When the job executer is at `e.s.n.p.StanfordCoreNLP - Adding annotator pos` it crashes after some time because it's running out of memory:

<details>
  <summary>Partial log</summary>

~~~
[ioapp-compute-1] INFO  d.j.s.LogSink - >>> 2020-09-24T22:31:59.571227Z Info GyJVT47C3.../process-item/High: Text extraction finished in 1794 ms
[ioapp-compute-3] INFO  d.j.s.LogSink - >>> 2020-09-24T22:31:59.604144Z Info GyJVT47C3.../process-item/High: Starting text analysis
[ioapp-compute-3] INFO  d.j.s.LogSink - >>> 2020-09-24T22:31:59.654125Z Info GyJVT47C3.../process-item/High: The text to analyse is larger than limit (1176 > 1). Analysing only first 1 characters.
[ioapp-compute-2] INFO  d.a.n.PipelineCache - Creating german Stanford NLP NER classifier...
[ioapp-compute-2] INFO  e.s.n.p.StanfordCoreNLP - Adding annotator tokenize
[ioapp-compute-2] INFO  e.s.n.p.StanfordCoreNLP - Adding annotator ssplit
[ioapp-compute-2] INFO  e.s.n.p.StanfordCoreNLP - Adding annotator mwt
[ioapp-compute-2] INFO  e.s.n.p.StanfordCoreNLP - Adding annotator pos
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:3821)
        at java.base/java.lang.StringLatin1.newString(StringLatin1.java:767)
        at java.base/java.lang.StringBuilder.toString(StringBuilder.java:447)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3694)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:3477)
        at java.base/java.io.ObjectInputStream.readString(ObjectInputStream.java:2041)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:517)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:475)
        at java.base/java.util.HashMap.readObject(HashMap.java:1551)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1216)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2381)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2215)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1707)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2520)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2414)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2215)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1707)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2520)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2414)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2215)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1707)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2111)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1695)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2520)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2414)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2215)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1707)
[blaze-selector-0] INFO  o.h.b.c.ServerChannel - Closing NIO1 channel /127.0.0.1:7878
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-1
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-2
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-3
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-4
[shutdownHook1] INFO  d.b.ops.ONode - Unregister app joex1
[ioapp-compute-1] INFO  c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated...
[ioapp-compute-1] INFO  c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed.
[ioapp-compute-1] INFO  o.h.c.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
docspell-joex.service: Main process exited, code=exited, status=1/FAILURE
docspell-joex.service: Failed with result 'exit-code'.
~~~
</details>

Because it was crashing of too low memory where there should be enough swap available I've tried the following things:

I've made sure as advised that
* `-Xmx500M` is set and
* the pool size is set to 1.

Because that part seemingly belongs to the text analyzing I've also
* disabled `regex-ner.enabled = false`,
* disabled `classification.enabled = false` and
* set `text-analysis.max-length = 1`.

Well, it's still crashing and even on a part that should be disabled? (I don't want to disable that, I just tried to circumvent the crash)
Do you can think of something why it's crashing even a device that should be a bit more powerful than a rPi?
Why is it's running out of memory when trying to analyze 1(!) character?

**Comment by eikek** [comment]
Hi @Lucki , thank you for reporting! I'll try to reproduce it. It could be that 500M is too low for the joex component now. Is your device capable to try a higher value? I'm using myself the UP-Board, that has 4G RAM. I configured the joex with 1.5G heap (e.g. `-Xmx1500m`). It is also running postgres and solr; it is sure now at its limits, but working well so far for me (single user). I think if you want to use classification and regex ner (this improves suggestions for correspondents etc), then using more heap is necessary now. I need to update the documentation there. OTOH if regex-ner is disabled, it would be possible to provide a more memory efficient way to initialize the pipeline as done in earlier versions (which however will not work as good)

In the recent version, the usage of the StanfordNLP library changed to be more in line with their documentation. The code that throws the OOM is still at initializing the pipeline – so there hasn't been any analysis done yet. The pipeline that would come out of this is then used to run all the text-analysis stuff, including NER and classification. That's why the `max-length` limit and the other settings are not used yet.

**Comment by Lucki** [comment]
> Is your device capable to try a higher value?

It has 2G ram. I've done some repartitioning and created a normal swap partition instead of using a dynamic swap file. It's now going through the whole classification process without a crash (`-Xmx50G`) besides the settings are still turned off.

It seems to have used around 3G in total (with other things running) process time was reported as 25:27.

I turned the settings back on and it seems to work in general. Sad it's that resource hungry, but that is what java is known for…

May I feature request:
* to skip processing and initializing parts that are disabled anyway?
* to adjust the documentation, 500M doesn't seem to be enough anymore.

**Comment by eikek** [comment]
Yes, it's resource hungry. But it's not Javas fault this time. The ML algorithms are those that need so much heap. The tesseract process is also quite resource hungry, which is written in C++. (This resource hungricity :) is one reason for having the rest-server and joex as separate components). 

Did you try with a lower value, maybe 1G or 1.5G heap? Maybe this reduces the time a little, or was the 50G necessary? Does the machine run other things, like SOLR or Postgres? Then 2G RAM is probably going to be difficult (requires swap then…).

Your requests are perfectly valid. I wasn't aware that initalizing the pipeline is so resource intensive already. I see if it is possible to use the previous way for the default ner tagging if everything is disabled.

Thank you for your input!

**Comment by Lucki** [comment]
> Maybe this reduces the time a little, or was the 50G necessary?

No, that's the swap partition size, I have it set to 5G currently and could probably go a bit lower but since…

> Does the machine run other things, like SOLR or Postgres? Then 2G RAM is probably going to be difficult (requires swap then…).

…I planned to run also other things (Kodi, calibre, …) on it I guess I have to remove the joex and solr from it. The other services are getting killed by systemd because they can't report back in time.
Guess the weekend task is to figure out how to expose the database if I want to experiment with this further.

**Comment by eikek** [comment]
Ah, thanks for the clarification, makes much more sense. Yeah, that sounds like a lot to handle for this board, since the joex component requires some resources…. If you don't want to have another thing running 24/7, an option could be to start joex on some workstation/laptop. Then documents are not processed when they arrive, but it may be ok depending on how often documents arrive or the laptop is on. 
If you want, just reach out via issues or chat with problems moving the database.

**Comment by Lucki** [comment]
> If you don't want to have another thing running 24/7, an option could be to start joex on some workstation/laptop. Then documents are not processed when they arrive, but it may be ok depending on how often documents arrive or the laptop is on.

That's what I've done now. Exposing the database was a bit tricky but I guess that's because I've never done anything with databases before…

**Comment by eikek** [comment]
If you want to try again, I can offer to help with that. It shouldn't be a lot of work, but depends on the specific setup of course.

**Comment by Lucki** [comment]
> If you want to try again, I can offer to help with that. It shouldn't be a lot of work, but depends on the specific setup of course.

No worries, I have a working setup now. Processing time is less than 20 seconds.
