### ISSUE TITLE
Invalid date 'FEBRUARY 30'

### ISSUE THREAD

**Issue by Lucki** [eikek/docspell#298]
I've uploaded a whole folder and one document failed. The document does not contain any date in february.

~~~
execution failed. Retrying later.: Invalid date 'FEBRUARY 30'
execution failed. Retrying later.: (conn=3795) Cannot delete or update a parent row: a foreign key constraint fails (`docspell`.`attachment_source`, CONSTRAINT `attachment_source_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `filemeta` (`id`))
execution failed. Retries exceeded.: (conn=3815) Cannot delete or update a parent row: a foreign key constraint fails (`docspell`.`attachment_source`, CONSTRAINT `attachment_source_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `filemeta` (`id`))
~~~

Although the document failed and isn't displayed anywhere in the UI it's blocking the reupload with the option "Skip files already present in docspell" set.

Unsetting the skip option allowed me to upload it and see it but there aren't any suggested meta:

~~~
execution failed. Retrying later.: Invalid date 'FEBRUARY 30'
Found existing item with these files.
execution failed. Retrying later.: 0
Found existing item with these files.
Processing failed on last retry. Creating item but without proposals.
execution failed. Retries exceeded.: 0
~~~

**Comment by eikek** [comment]
Thank you a lot for reporting these! I don't have an idea right now what could cause this. Are there any stacktraces in the logs? If it is possible to share the document, that would be great, but I know that it is usually not possible.

**Comment by Lucki** [comment]
Unfortunately it's not possible to share that document.

<details><summary>Stacktrace</summary>

~~~
[ioapp-compute-3] ERROR d.j.s.SchedulerImpl - Job 3kwKjdeHf.../process-item/High execution failed. Retrying later.
java.time.DateTimeException: Invalid date 'FEBRUARY 30'
        at java.time.LocalDate.create(LocalDate.java:431)
        at java.time.LocalDate.of(LocalDate.java:269)
        at docspell.analysis.date.DateFind$SimpleDate.toLocalDate(DateFind.scala:38)
        at docspell.analysis.date.DateFind$.$anonfun$findDates$3(DateFind.scala:24)
        at scala.Option.map(Option.scala:242)
        at docspell.analysis.date.DateFind$.$anonfun$findDates$2(DateFind.scala:22)
        at fs2.Chunk$Singleton.map(Chunk.scala:527)
        at fs2.internal.FreeC$Output.$anonfun$mapOutput$2(Algebra.scala:270)
        at fs2.internal.FreeC$$anon$7.cont(Algebra.scala:181)
        at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.<init>(Algebra.scala:222)
        at fs2.internal.FreeC$ViewL$$anon$9.cont(Algebra.scala:222)
        at fs2.internal.FreeC$ViewL$.mk(Algebra.scala:213)
        at fs2.internal.FreeC$ViewL$.apply(Algebra.scala:202)
        at fs2.internal.FreeC.viewL(Algebra.scala:86)
        at fs2.internal.FreeC$.go$1(Algebra.scala:399)
        at fs2.internal.FreeC$.$anonfun$compile$8(Algebra.scala:449)
        at fs2.internal.FreeC$.$anonfun$compile$1(Algebra.scala:415)
        at cats.effect.SyncIO.$anonfun$flatMap$1(SyncIO.scala:74)
        at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:244)
        at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:244)
        at cats.effect.IO.unsafeRunTimed(IO.scala:327)
        at cats.effect.IO.unsafeRunSync(IO.scala:246)
        at cats.effect.SyncIO.unsafeRunSync(SyncIO.scala:51)
        at fs2.Stream$PureOps$.to_$extension(Stream.scala:3910)
        at fs2.Stream$PureOps$.toVector$extension(Stream.scala:3923)
        at docspell.analysis.TextAnalyser$$anon$1.$anonfun$dateNer$1(TextAnalyser.scala:78)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
        at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
        at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:90)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:70)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:50)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
        at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:43)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
        at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:352)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:124)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~
</details>

**Comment by eikek** [comment]
No problem and thanks for the stacktrace, this helps! It seems that this date was recognized for some reason. Simply forgot to check for invalid date patterns…
