### ISSUE TITLE
docspell-restserver fails to open H2 database connection

### ISSUE THREAD

**Issue by ebertland** [eikek/docspell#336]
I installed docspell today using the deb packages (0.12.0). I am running Debian 10 (buster). I have the openjdk-11-jre package installed. After seeing the error message, I installed libh2-java as well, but the error was identical.

```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)
```
```
ii  libh2-java     1.4.197-4    all          H2 Database Engine
ii  libh2-java-doc 1.4.197-4    all          H2 Database Engine (documentation)
ii  openjdk-11-jre:amd64          11.0.8+10-1~deb10u1 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64 11.0.8+10-1~deb10u1 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```
I have not yet edited any configuration files or systemd files. I simply enabled and started docspell-restserver and docspell-joex.

```
Oct 17 15:06:08 iron docspell-restserver[18535]: [main] INFO  d.r.Main - Using config file from system properties: /usr/share/docspell-restserver/bin/../conf/docspell-server.conf
Oct 17 15:06:09 iron docspell-restserver[18535]: [main] INFO  d.r.Main -
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  ______                          _ _
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  |  _  \                        | | |
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  | | | |___   ___ ___ _ __   ___| | |
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>                      | |
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>                      |_| v0.12.0 (#f40eb15e)
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  << REST Server >>
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  Id:       rest1
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  Base-Url: http://localhost:7880
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  Database: jdbc:h2:///tmp/docspell-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  Fts:      -
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>  Config:   /usr/share/docspell-restserver/bin/../conf/docspell-server.conf
Oct 17 15:06:09 iron docspell-restserver[18535]: ***>
Oct 17 15:06:11 iron docspell-restserver[18535]: [ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations...
Oct 17 15:06:11 iron docspell-restserver[18535]: [ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/h2)
Oct 17 15:06:11 iron docspell-restserver[18535]: [ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 6.5.7 by Redgate
Oct 17 15:06:12 iron docspell-restserver[18535]: org.flywaydb.core.internal.exception.FlywaySqlException:
Oct 17 15:06:12 iron docspell-restserver[18535]: Unable to obtain connection from database (jdbc:h2:///tmp/docspell-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE) for user 'sa': Feature not supported: "autoServerMode && (readOnly || fileLockMethod =
Oct 17 15:06:12 iron docspell-restserver[18535]: --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Oct 17 15:06:12 iron docspell-restserver[18535]: SQL State  : HYC00
Oct 17 15:06:12 iron docspell-restserver[18535]: Error Code : 50100
Oct 17 15:06:12 iron docspell-restserver[18535]: Message    : Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == FS || inMemory)" [50100-200]
Oct 17 15:06:12 iron docspell-restserver[18535]:         at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:65)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at org.flywaydb.core.Flyway.execute(Flyway.java:453)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at org.flywaydb.core.Flyway.repair(Flyway.java:384)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:34)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:90)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:70)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:50)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:43)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:352)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:124)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Oct 17 15:14:52 iron docspell-restserver[19228]:         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ebertland** [comment]
Is there a support channel, such as on reddit, discord, matrix?

**Comment by eikek** [comment]
Hi @ebertland, thanks for reporting this! I'll take a look. Can't say right now, what the problem is. Did you use a new install, or was it an upgrade from an earlier version (iow: is it a new database or an existing one)?

For support is best to use this issue tracker on github, or the [gitter room](https://gitter.im/eikek/docspell) (this is a spare time project, so there is no such thing as "official support"; I try to answer as fast as possible, but no guarantees).

**Comment by ebertland** [comment]
It's a new installation, not an upgrade. I am currently building the docker container, and I'll let you know if that works better.

**Comment by ebertland** [comment]
The docker container works.

**Comment by ebertland** [comment]
This appears to be a permission problem with the database. There is a different user created for each debian package: docspell-restserver and docspell-joex. They both need access to the H2 database. Whoever creates it first owns the files (.mv.db and .lock.db), and then the other process fails to start with an error like the one in the description.

If I chmod both database files to 666 after they are created (they were 644), then the second process works successfully. I don't know enough about H2 to say what the correct fix is for this problem. My current plan is to use the same user for both processes.

**Comment by eikek** [comment]
Ah yes, this is indeed the problem. The h2 db uses a single file as database, it must be read- and writable by both processes. I see if I can have the deb packages declaring the same user

**Comment by sortedcord** [comment]
Im having the same issue, and im not running it in a docker container... What permission should I grant and on which file?

**Comment by eikek** [comment]
Oh strange. The owner of the files should be the user that runs the process. You must use the same user for joex and restserver then, because they both need access to the same file.
