### ISSUE TITLE
No files shown

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#472]
When opening the home screen I get these errors and no files. I am on latest (_Docspell 0.16.0-SNAPSHOT (#1874eb44)_)

```
docspell-app.js:4986 GET http://docs.home/api/v1/sec/customfield?q= 500 (Internal Server Error)
(anonymous) @ docspell-app.js:4986
_Scheduler_step @ docspell-app.js:1810
_Scheduler_enqueue @ docspell-app.js:1784
_Scheduler_rawSend @ docspell-app.js:1730
_Platform_dispatchEffects @ docspell-app.js:2102
_Platform_enqueueEffects @ docspell-app.js:2088
_Platform_initialize @ docspell-app.js:1889
(anonymous) @ docspell-app.js:4037
(anonymous) @ docspell-app.js:20
(anonymous) @ docspell.js:23
docspell.js:55 Requesting ui settings
docspell-app.js:4986 POST http://docs.home/api/v1/sec/item/searchWithTags 500 (Internal Server Error)
(anonymous) @ docspell-app.js:4986
_Scheduler_step @ docspell-app.js:1810
_Scheduler_enqueue @ docspell-app.js:1784
_Scheduler_rawSend @ docspell-app.js:1730
_Platform_dispatchEffects @ docspell-app.js:2102
_Platform_enqueueEffects @ docspell-app.js:2088
_Platform_initialize @ docspell-app.js:1889
(anonymous) @ docspell-app.js:4037
(anonymous) @ docspell-app.js:20
(anonymous) @ docspell.js:23
[Violation] Forced reflow while executing JavaScript took 91ms
```

**Comment by eikek** [comment]
Oh noes… Do you have any server logs maybe? (from the restserver component)

**Comment by totti4ever** [comment]
```
[ioapp-compute-0] ERROR d.s.i.DoobieMeta - SQL Failure: ExecFailure(SELECT  cf.id , cf.name , cf.label , cf.ftype , cvf.field_value  FROM  custom_field_value cvf INNER JOIN custom_field cf ON cvf.field = cf.id  WHERE  cvf.item_id  = ? ,List(Ident(4XBrDmghWFp-BMzhfzRxARS-zFsqM1WRYHz-oPyFSBxqjqF)),3293091 nanoseconds,java.sql.SQLSyntaxErrorException: (conn=4388) Table 'docspell.custom_field_value' doesn't exist)
[ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchWithTags
[ioapp-compute-1] INFO  o.h.s.m.Logger - service raised an error: class java.sql.SQLSyntaxErrorException
[ioapp-compute-1] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/searchWithTags from 172.16.0.10
java.sql.SQLSyntaxErrorException: (conn=4388) Table 'docspell.custom_field_value' doesn't exist
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:956)
        at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
        at evalOn @ doobie.util.transactor$Transactor$fromDataSource$FromDataSourceUnapplied.$anonfun$apply$13(transactor.scala:280)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at bracketCase @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:163)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'docspell.custom_field_value' doesn't exist
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:956)
        at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:103)
        at cats.effect.internals.IORunLoop$.restartCancelable(IORunLoop.scala:50)
        at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:100)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:80)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:58)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:177)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:476)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: Table 'docspell.custom_field_value' doesn't exist
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1683)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1545)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1508)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
        ... 30 common frames omitted
```

**Comment by eikek** [comment]
Very strange: the current snapshot should have db version 1.13, these lines are suspicious:
> [ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Current version of schema `docspell`: 1.12.0
> [ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Schema `docspell` is up to date. No migration necessary.

The migration to version 1.13.0 didn't happen as it seems. Not sure why… I can look into it a little more tonight. You could check the contents of the table `flyway_migration` – is 1.12 really latest change?

**Comment by totti4ever** [comment]
1.12.0 - installed 13th of November, indeed

**Comment by eikek** [comment]
This is postgres right? I just realized, I forgot to add the migration for mariadb and h2 :( but this doesn't affect postgres, which is included in current [master](https://github.com/eikek/docspell/blob/master/modules/store/src/main/resources/db/migration/postgresql/V1.13.0__custom_fields.sql)

**Comment by totti4ever** [comment]
it is maria

**Comment by eikek** [comment]
Should be fixed with recent commits in master.

**Comment by totti4ever** [comment]
fixed!
