### ISSUE TITLE
Gmail with app-specific passwords

### ISSUE THREAD

**Issue by bjeanes** [eikek/docspell#520]
The docs say that for Gmail you need to create an OAuth application and create tokens and deal with refreshing, etc.

However, Google offers app-specific passwords (https://myaccount.google.com/apppasswords) for this kind of use-case. 

I generated some credentials here and used `imap-cli` (https://github.com/Gentux/imap-cli) to make sure they worked. `imap-cli` correctly lists my emails so the credentials are accepted by Google. However, when I add them as an IMAP setting in Docspell, the job execution continues to fail with 

```
2020-12-26T11:56:43: Job FMmiFZqnP.../bjeanes/scan-mailbox/Low execution failed. Retrying later.: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
javax.mail.AuthenticationFailedException: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:708)
        at javax.mail.Service.connect(Service.java:364)
        at javax.mail.Service.connect(Service.java:222)
        at javax.mail.Service.connect(Service.java:243)
        at emil.javamail.internal.ConnectionResource$.createImapStore(ConnectionResource.scala:44)
        at emil.javamail.internal.ConnectionResource$.$anonfun$make$1(ConnectionResource.scala:32)
        at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
        at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
        at use @ docspell.joex.Main$.run(Main.scala:59)
        at map @ docspell.joex.scanmailbox.ScanMailboxTask$.processFolder$1(ScanMailboxTask.scala:90)
        at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at map @ docspell.joex.scanmailbox.ScanMailboxTask$.importMails(ScanMailboxTask.scala:77)
        at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
```

Is there some reason why this would be failing? Ideally this would work and the docs could be updated to reflect this approach. This is how I connect to my email account via IMAP from other protocols...

**Comment by eikek** [comment]
Hi @bjeanes and thank you a lot for this heads up! I just didn't know about these app specific passwords. I researched a little back then, but they didn't show up for me. I don't know why this is failing right now. I will try to reproduce it and see if I can add support for these passwords. It depends on what kind of auth mechanism this uses at the end and if this is supported by javamail.

You could set the mail.debug setting to true in the joex config (`docspell.joex.mail-debug`) and see if that gives more clues about the cause.

**Comment by bjeanes** [comment]
Thanks!

It should be accepted as if it were a password. Regular SSL IMAP

**Comment by eikek** [comment]
Ok, then I don't see why it shouldn't "just work"…. But maybe there is some setting missing that prevents javamail from using some possible auth mechanism. i'll need to take a deeper look.

**Comment by eikek** [comment]
So I found out what happens. The javamail library uses the advertised auth mechanisms in a specified order. If you wanted to use xoauth2, then it must be put as first try, because otherwise using e.g. PLAIN would fail. Now with app-passwords it's the opposite: i put xoauth2 as first mechanism to try if present (just for those that advertise xoauth2, like gmail) and now it should use PLAIN instead with the app-specific password.

I need to change the imap settings so the user must specify whether to use oauth2 or not. I think the default case is to use an app-specific password, although that means to enable 2fa in google (which can mean to given them your mobile number…).

**Comment by bjeanes** [comment]
Whoa app-specific passwords are disabled if you don't have 2FA enabled? I had no idea! I have 2FA enabled (yes, giving Google your mobile sucks, but 2FA was too important to me, especially for email).

**Comment by bjeanes** [comment]
FWIW, Google does let you use non-phone-based MFA options. However, IIRC, it requires you set up phone-based first. So you could use a throwaway Twilio address or something, then set up with a token or code generator...

**Comment by eikek** [comment]
> Whoa app-specific passwords are disabled if you don't have 2FA enabled? I had no idea! I have 2FA enabled (yes, giving Google your mobile sucks, but 2FA was too important to me, especially for email).

Yes, that was the case today when I tried it. I don't like this either, and I didn't understand why this is a requirement for app-specific passwords (you can for example allow "insecure auth" without it).

> FWIW, Google does let you use non-phone-based MFA options. However, IIRC, it requires you set up phone-based first. So you could use a throwaway Twilio address or something, then set up with a token or code generator...

Yes, definitely– it is not restricted to a phone! For me today, I had the choice between sms/call and some usb dongle. There might be more options, since I don't use gmail really, I never really looked at it.

**Comment by bjeanes** [comment]
> Yes, definitely– it is not restricted to a phone!

Exactly. I have a Yubikey and a regular TOTP app configured on my Google account. I resent that they force using phone as a MFA because that is the least secure (too vulnerable to social engineering, including porting a number away from the owner)

**Comment by bjeanes** [comment]
When do you think you'll get a new Docker image for this so that I might test it?

**Comment by eikek** [comment]
The master branch (which reflects current state of dev) is also published on docker-hub automatically. You could use this to test (thank you!!). It is the `SNAPSHOT` tag instead of `LATEST`. I'd either do a db backup before or use a new db. The master branch is currently the release candidate for 0.18 – But I'm just about to start testing, so things might change there.

**Comment by bjeanes** [comment]
Fortunately I only have a handful of documents so far, so a DB issue isn't a dealbreaker. I'll test it on the weekend. Thanks!

**Comment by bjeanes** [comment]
Heya! I just wanted to report that it is able to successfully communicate with my IMAP server now!

Unfortunately, I have a different issue where it appears to just continually loop on the first 50 items, instead of progressing to next 50, but I'll open a separate issue.
