### ISSUE TITLE
SQL error with "Fulltext Search" using MySQL

### ISSUE THREAD

**Issue by aelsenaar** [eikek/docspell#599]
Hi,

I am testing Docspell on a Docker swarm and using MariaDB as a database backend. Most of the functionality seems to work fine. Only the "Fulltext Search" results in the following SQL syntax error.

`2021-01-26T18:16:31.534373079Z [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats 
2021-01-26T18:16:31.534495975Z [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
2021-01-26T18:16:31.540907385Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats 
2021-01-26T18:16:31.540936015Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
2021-01-26T18:16:33.094958445Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchWithTags 
2021-01-26T18:16:33.094985799Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
2021-01-26T18:16:37.285683504Z [docspell-restserver-17] INFO  d.r.r.ItemRoutes - Make index only summary: ItemFtsSearch(0,200,diploma) 
2021-01-26T18:16:37.337538765Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchWithTags 
2021-01-26T18:16:37.337567779Z [ioapp-compute-3] INFO  o.h.s.m.Logger - service raised an error: class java.sql.SQLSyntaxErrorException 
2021-01-26T18:16:37.343313111Z [ioapp-compute-3] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/searchWithTags from 10.0.25.2 
2021-01-26T18:16:37.343345782Z java.sql.SQLSyntaxErrorException: (conn=9764) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('ARZJKdaNZG4-RxyLzNdufJe-jDiDiFx8hha-SUHz29jY1nA', 2.6099906) , ('EGZjgQ1HnKc-q' at line 1
2021-01-26T18:16:37.343365763Z 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
2021-01-26T18:16:37.343372376Z 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
2021-01-26T18:16:37.343377671Z 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
2021-01-26T18:16:37.343398329Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
2021-01-26T18:16:37.343404001Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
2021-01-26T18:16:37.343409133Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
2021-01-26T18:16:37.343414383Z 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
2021-01-26T18:16:37.343419701Z 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
2021-01-26T18:16:37.343424884Z 	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:953)
2021-01-26T18:16:37.343429571Z 	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:109)
2021-01-26T18:16:37.343434365Z 	at evalOn @ doobie.util.transactor$Transactor$fromDataSource$FromDataSourceUnapplied.$anonfun$apply$13(transactor.scala:294)
2021-01-26T18:16:37.343439553Z 	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:167)
2021-01-26T18:16:37.343444889Z 	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
2021-01-26T18:16:37.343450254Z 	at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:167)
2021-01-26T18:16:37.343455767Z 	at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
2021-01-26T18:16:37.343462563Z 	at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
2021-01-26T18:16:37.343467560Z 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
2021-01-26T18:16:37.343472277Z 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
2021-01-26T18:16:37.343477115Z 	at flatMap @ fs2.internal.CompileScope.$anonfun$open$2(CompileScope.scala:146)
2021-01-26T18:16:37.343482002Z 	at flatMap @ fs2.internal.CompileScope.open(CompileScope.scala:141)
2021-01-26T18:16:37.343486859Z 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$15(Algebra.scala:533)
2021-01-26T18:16:37.343491732Z 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$14(Algebra.scala:531)
2021-01-26T18:16:37.343496661Z 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
2021-01-26T18:16:37.343501228Z 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
2021-01-26T18:16:37.343506632Z 	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
2021-01-26T18:16:37.343511776Z Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('ARZJKdaNZG4-RxyLzNdufJe-jDiDiFx8hha-SUHz29jY1nA', 2.6099906) , ('EGZjgQ1HnKc-q' at line 1
2021-01-26T18:16:37.343527196Z 	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
2021-01-26T18:16:37.343533309Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
2021-01-26T18:16:37.343538915Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
2021-01-26T18:16:37.343544383Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
2021-01-26T18:16:37.343549637Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
2021-01-26T18:16:37.343555404Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
2021-01-26T18:16:37.343560293Z 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
2021-01-26T18:16:37.343565188Z 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
2021-01-26T18:16:37.343570217Z 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
2021-01-26T18:16:37.343574837Z 	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:953)
2021-01-26T18:16:37.343580899Z 	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:109)
2021-01-26T18:16:37.343586398Z 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
2021-01-26T18:16:37.343591121Z 	at cats.effect.internals.IORunLoop$.restartCancelable(IORunLoop.scala:51)
2021-01-26T18:16:37.343596157Z 	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:100)
2021-01-26T18:16:37.343602114Z 	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
2021-01-26T18:16:37.343607403Z 	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
2021-01-26T18:16:37.343612495Z 	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
2021-01-26T18:16:37.343619075Z 	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
2021-01-26T18:16:37.343625095Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2021-01-26T18:16:37.343630095Z 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
2021-01-26T18:16:37.343635215Z 	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
2021-01-26T18:16:37.343640348Z 	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
2021-01-26T18:16:37.343645464Z 	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
2021-01-26T18:16:37.343650800Z 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:80)
2021-01-26T18:16:37.343655907Z 	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:58)
2021-01-26T18:16:37.343668121Z 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
2021-01-26T18:16:37.343674346Z 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
2021-01-26T18:16:37.343679445Z 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
2021-01-26T18:16:37.343700733Z 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
2021-01-26T18:16:37.343707490Z 	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
2021-01-26T18:16:37.343713303Z 	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
2021-01-26T18:16:37.343718369Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-26T18:16:37.343723760Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-26T18:16:37.343728524Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-26T18:16:37.343735424Z Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('ARZJKdaNZG4-RxyLzNdufJe-jDiDiFx8hha-SUHz29jY1nA', 2.6099906) , ('EGZjgQ1HnKc-q' at line 1
2021-01-26T18:16:37.343741665Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1683)
2021-01-26T18:16:37.343746905Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1545)
2021-01-26T18:16:37.343752157Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1508)
2021-01-26T18:16:37.343757756Z 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
2021-01-26T18:16:37.343763334Z 	... 30 common frames omitted
2021-01-26T18:16:37.371703839Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats 
2021-01-26T18:16:37.371735166Z [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK `

Is there something I can do to find the actual cause of this SQL error?

**Comment by eikek** [comment]
Hi @aelsenaar , thank you for reporting! This looks like  a problem when resolving the results from solr against the database. Is your search query rather unspecific, so that it is likely that a lot of results are returned? Or how many results would you think are returned from the search? I'm going to look into it.

**Comment by aelsenaar** [comment]
Hi @eikek , the query is very specific. The strange thing is that the number of results in the top of the screen is updated. See the two attached screenshots:

![01- results_no_query](https://user-images.githubusercontent.com/16883460/105901034-181ffe00-601d-11eb-9c46-49a2ed595660.png)
![02- results_diploma_query](https://user-images.githubusercontent.com/16883460/105901039-18b89480-601d-11eb-81bf-ad2ff010f222.png)

**Comment by eikek** [comment]
The stats are queried a bit differently, since order doesn't matter etc and some other things can be simplified. This is the last line in your logs, the request to `/searchStats` which succeeds. That's why you see the stats updated :-)

Unfortunately, I can't reproduce it here. I played a bit with my mariadb instance. I have mariadb 10.4.15, which one do you use? Did this work in a previous version (if applicable) and is this the newest currently?

Since it complains about invalid sql, there is probably a bug in the query builder. If you could run this with more extensive logging enabled, the complete query should be logged.  If you have time for this, that'd be great! It shouldn't contain anything really sensible, only item IDs. You can send it via email or matrix in case you don't like to put it here.

It requires to provide a log config file: You'd need to create a xml file, say `logback.xml`, with the following content:
``` xml
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <withJansi>true</withJansi>

    <encoder>
      <pattern>[%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n</pattern>
    </encoder>
  </appender>

  <logger name="docspell" level="debug" />
  <logger name="emil" level="debug"/>
  <logger name="docspell.store.queries.QItem" level="trace"/>

  <root level="INFO">
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```

This is the default log config with this line added:   `<logger name="docspell.store.queries.QItem" level="trace"/>`. Then it is necessary to provide this file to the program using `/path/to/docspell-server -Dlogback.configurationFile=/path/to/logback.xml`.

Another thing worth a try is rebuilding the entire index. You can do this via a post request, as described [here](https://docspell.org/docs/configure/#full-text-search-solr).

Thank you!

**Comment by aelsenaar** [comment]
I don't know if it makes any difference but I just realize I use MySQL version 8.0.23.

During my testing this Fulltext Search never worked in my environment yet.

I tried rebuilding the entire index but that does not solve the problem. :-(

I am a bit confused about the way I have to provide the log configuration. I am running docspell in Docker container using a docker-compose configuration. Where should I provide the option for the extra log configuration?

**Comment by eikek** [comment]
> I don't know if it makes any difference but I just realize I use MySQL version 8.0.23.

Oh I'm not sure if that is possible at all – I only have MariaDB. I don't know about the differences well enough to say that it could work with MySQL. I can't test it with MySQL, because I don't have it.


> I am a bit confused about the way I have to provide the log configuration. I am running docspell in Docker container using a docker-compose configuration. Where should I provide the option for the extra log configuration?

Well, I'm also confused as to how convince docker-compose to start it with a different argument :). I'm not using docker myself….  I _think_ that you can define the startup command again in the compose file:

``` yaml
  restserver:
    image: eikek0/docspell:restserver-LATEST
    container_name: docspell-restserver
    restart: unless-stopped
    entrypoint:
      - "/opt/restserver-entrypoint.sh"
      - "-Dlogback.configurationFile=/opt/logback.xml"
      - "/opt/docspell.conf"
    ports:
      - "7880:7880"
    volumes:
      - ./docspell.conf:/opt/docspell.conf
      - ./logback.xml:/opt/logback.xml
    env_file: ./.env
    depends_on:
      - solr
```

Then you'd need to put the `logback.xm` next to the config file. OTOH I'm not sure if it's worth it. I can only test with MariaDB anyways….

**Comment by aelsenaar** [comment]
I was able to add the log configuration the the docker configuration as in your example. Great! :)

I got the following logging:

`
[ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
[docspell-restserver-blocking-5] TRACE d.s.q.QItem - fts query: Fragment("WITH tids(item_id, weight) AS (VALUES (?, ?) , (?, ?) , (?, ?) , (?, ?) , (?, ?) , (?, ?) , (?, ?) )  SELECT DISTINCT i.itemid, i.name, i.state, COALESCE(i.itemdate, i.created) , i.duedate, i.source, i.incoming, i.created, COALESCE(cta.num, ? ) , o.oid, o.name, pers0.pid, pers0.name, pers1.pid, pers1.name, e.eid, e.name, f.id, f.name, SUBSTRING(i.notes FROM ? FOR ?) , i.created, tw.weight FROM item i LEFT JOIN folder f ON (f.id = i.folder_id AND f.cid = ? ) LEFT JOIN  (SELECT COUNT(*) AS num , a.itemid AS item_id  FROM attachment a INNER JOIN item i ON i.itemid = a.itemid WHERE i.cid = ? GROUP BY a.itemid) AS cta  ON cta.item_id = i.itemid LEFT JOIN person pers0 ON (pers0.pid = i.corrperson AND pers0.cid = ? ) LEFT JOIN organization o ON (o.oid = i.corrorg AND o.cid = ? ) LEFT JOIN person pers1 ON (pers1.pid = i.concperson AND pers1.cid = ? ) LEFT JOIN equipment e ON (e.eid = i.concequipment AND e.cid = ? ) INNER JOIN tids tw ON tw.item_id = i.itemid WHERE (i.cid = ?  AND (i.folder_id is null  OR i.folder_id IN (SELECT f.id FROM folder f INNER JOIN user_ u ON f.owner = u.uid WHERE (f.cid = ?  AND u.login = ? ) UNION ALL SELECT m.folder_id FROM folder_member m INNER JOIN folder f ON f.id = m.folder_id INNER JOIN user_ u ON u.uid = m.user_id WHERE (f.cid = ?  AND u.login = ? )))) ORDER BY tw.weight DESC ") 
[ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchWithTags 
[ioapp-compute-0] INFO  o.h.s.m.Logger - service raised an error: class java.sql.SQLSyntaxErrorException 
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
[ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats 
[ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
[ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 GET / 
[ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 303 See Other 
[ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 GET /app 
[ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK 
[ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 GET /sw.js 
[ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK
 `

Can you check if you see something strange? If you still suspect MySQL as the source of the problem I can try to migrate to MariaDB and test again.

**Comment by eikek** [comment]
I tried this query with mariadb and it didn't complain to me :-/ 

I just found a post that MySQL doesn't support the `VALUES` table constructor. But MariaDB does support this from version 10.3+. (found [on stackexchange](https://dba.stackexchange.com/questions/177312/does-mariadb-or-mysql-implement-the-values-expression-table-value-constructor#answer-202466) – PostgreSQL is no problem as usual and even H2 understands this. I'm surprised that MySQL doesn't.

**Comment by aelsenaar** [comment]
I was able to migrate (export/import) my docspell data to MariaDB (Using version 10.4.17. Version 10.5 resulted in a warning).

Now, the Fulletext search in DocSpell is working fine. So, it looks like MySQL is the root cause of this problem. Was not expecting that. :-(

**Comment by eikek** [comment]
Yes, it surprises me, too. MySQL is intentionally not supported currently. I sometimes feel that 3 DBs are already too much:-)

**Comment by aelsenaar** [comment]
True, 3 DB's is already too much! ;-) I will stay at MariaDB for now. Thanks for the support.
