### ISSUE TITLE
Docker build fails, but reports success

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#635]
The docker build failed to build the app due to  a missing program (npm) at build time:

```
[error] java.io.IOException: Cannot run program "npm" (in directory "/src/docspell"): error=2, No such file or directory
[error] at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error] at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error] at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
```

but the whole process finished successfully - dockerhub reports `SUCCESS`.

![Selection_123](https://user-images.githubusercontent.com/701128/107886581-ec4bb600-6f00-11eb-904b-1fed3718d684.png)

**Comment by eikek** [comment]
Now obsoleted in pr #840
