### ISSUE TITLE
Race condition on database upgrade

### ISSUE THREAD

**Issue by tobru** [eikek/docspell#716]
When I upgrade Docspell on my Kubernetes deployment it looks like restserver and joex wants to upgrade the database on startup and lock each other to the point where I have to restart the database completely.

Output on both of the applications is the same:

```
[ioapp-compute-0] ERROR o.f.c.i.d.p.PostgreSQLAdvisoryLockTemplate - Unable to release PostgreSQL advisory lock 
[ioapp-compute-0] INFO  o.h.c.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false 
org.flywaydb.core.api.FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount' configuration option: https://flywaydb.org/documentation/configuration/parameters/lockRetryCount
	at org.flywaydb.core.internal.strategy.RetryStrategy.doWithRetries(RetryStrategy.java:87)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.lock(PostgreSQLAdvisoryLockTemplate.java:86)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:36)
	at map @ docspell.store.impl.StoreImpl.migrate(StoreImpl.scala:25)
	at liftF @ docspell.joex.JoexServer$.stream(JoexServer.scala:31)
	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$4(CompileScope.scala:185)
	at flatten @ fs2.internal.ScopedResource$$anon$1.acquired(ScopedResource.scala:139)
	at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$1(CompileScope.scala:183)
	at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
```

And on the database:

```
2021-03-14 08:51:16.866 UTC [9361] WARNING:  you don't own a lock of type ExclusiveLock
```

After a restart of the database and both apps everything comes up in a clean way.

As a sidenote: The [deployment of the two apps is configured as `Recreate` strategy](https://git.tbrnt.ch/tobru/gitops-tbrnt/src/branch/master/docspell/restserver/deployment.yaml#L13) which means that the old version of the application is stopped before the new image is started again, that makes sure that the old version doesn't access the database the same time as the new version is starting up and upgrading the database.

**Comment by eikek** [comment]
Oh, this never happened to me. I had the impression, flyway (the library that manages the db migrations) already takes appropriate measures here. From what I just  [read](https://flywaydb.org/documentation/configuration/parameters/lockRetryCount), it takes a lock retrying a few times. This error is raised if it could not take the lock within the configured retries. Maybe it's not retrying often enough for some situations. One could raise this limit or disable it via env variable `FLYWAY_LOCK_RETRY_COUNT=-1` (not tested).

But since both apps are not able to take the lock, I'm not sure about the cause here. Is there maybe some other process still involved?

**Comment by tobru** [comment]
Do you happen to know how I can check for the lock? I'll do a better investigation on the next upgrade and see what I can find out and will report back :+1:

**Comment by eikek** [comment]
No, not from the top of my head. I'm sure there are some system tables that could be queried, but I'd need to look it up in the docs first.

**Comment by tobru** [comment]
No worries, I'll figure that out then :+1:

**Comment by tobru** [comment]
It happened again with the `0.21.0` -> `0.22.0` upgrade:

```
# k -n docspell logs -f restserver-579477d94b-2v7m8
[main] INFO  d.r.Main - Using given config file: /etc/docspell/docspell.conf 
[main] INFO  d.r.Main - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.22.0 (#1492800b)
***>  << REST Server >>
***>  Id:       restserver-579477d94b-2v7m8
***>  Base-Url: https://docs.tobru.ch
***>  Database: jdbc:postgresql://postgres:5432/docspell
***>  Fts:      http://solrtcp:8983/solr/docspell
***>  Config:   /etc/docspell/docspell.conf
***>   
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations... 
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/postgresql) 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.7.3 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.d.b.DatabaseType - Database: jdbc:postgresql://postgres:5432/docspell (PostgreSQL 13.2) 
[ioapp-compute-0] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary. No failed migration detected. 
[ioapp-compute-0] INFO  o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.119s). 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.7.3 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.c.DbValidate - Successfully validated 32 migrations (execution time 00:00.031s) 
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Current version of schema "public": 1.21.1 
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Migrating schema "public" to version "1.22.0 - add task name"
```

```
# k -n docspell logs -f joex-5dc6bcdbf7-qn548
Starting unoconv listener
[main] INFO  d.joex.Main - Using given config file: /etc/docspell/docspell.conf 
[main] INFO  d.joex.Main - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.22.0 (#1492800b)
***>  << JOEX >>
***>  Id:       joex-joex-5dc6bcdbf7-qn548
***>  Base-Url: http://joex:7878
***>  Database: jdbc:postgresql://postgres:5432/docspell
***>  Fts:      http://solrtcp:8983/solr/docspell
***>  Config:   /etc/docspell/docspell.conf
***>   
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations... 
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/postgresql) 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.7.3 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.d.b.DatabaseType - Database: jdbc:postgresql://postgres:5432/docspell (PostgreSQL 13.2) 
[ioapp-compute-0] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary. No failed migration detected. 
[ioapp-compute-0] INFO  o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.040s). 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.7.3 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.c.DbValidate - Successfully validated 32 migrations (execution time 00:00.015s) 
[ioapp-compute-0] ERROR o.f.c.i.d.p.PostgreSQLAdvisoryLockTemplate - Unable to release PostgreSQL advisory lock 
[ioapp-compute-0] INFO  o.h.c.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false 
org.flywaydb.core.api.FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount' configuration option: https://flywaydb.org/documentation/configuration/parameters/lockRetryCount
        at org.flywaydb.core.internal.strategy.RetryStrategy.doWithRetries(RetryStrategy.java:87)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.lock(PostgreSQLAdvisoryLockTemplate.java:86)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:192)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:572)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:36)
        at map @ docspell.store.impl.StoreImpl.migrate(StoreImpl.scala:25)
        at eval @ docspell.joex.JoexServer$.stream(JoexServer.scala:31)
        at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$4(CompileScope.scala:185)
        at flatten @ fs2.internal.ScopedResource$$anon$1.acquired(ScopedResource.scala:139)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$1(CompileScope.scala:183)
        at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
```

```
2021-04-16 18:35:40.979 UTC [23789] WARNING:  you don't own a lock of type ExclusiveLock
```

So it looks like `restserver` was a bit faster and did the upgrade. After some time the message on Postgres appeared and then both apps and the db got stuck.

I tried to research a bit if I can find out more, but I haven't had success until now. I'll try it again the next time :+1:

**Comment by eikek** [comment]
Thanks for the update! Really strange to me. I could make the lockRetryCount better configurable. But I doubt it would help. According to flyway docs, it tries to obtain the advisory lock 50 times in 1s interval. This should be way more than enough…. And it seems I forgot to add timestamps to the logs 🤦🏼  do you think it took that long until the error happened?

It says "unable to release lock" - I first thought the problem is more releasing the lock, but I think it is due to not being able to obtain the lock in the first place. Releasing is always tried, even when acquiring fails. 

I only found the [release notes](https://flywaydb.org/documentation/learnmore/releaseNotes#7.5.2) of flyway 7.5.2 mention some fix that might be related. I also find it strange that it never occurs on my machine, as I'm developing against postgres from day 1 (but now version 12) - I should have run into this by now, too.

You could try to read from `pg_locks` to see if there is an advisory lock, maybe this reveals something. If I do `select pg_try_advisory_lock(1)` for example, it looks like this:

``` sql
docspell=> select l.locktype,d.datname,l.relation,l.pid from pg_locks l inner join pg_database d on l.database = d.oid;
 locktype | datname  | relation | pid
----------+----------+----------+------
 relation | docspell |    11645 | 3262
 advisory | docspell |          | 3262
(2 rows)
```

I think the postgresql warning is due to trying to release a non-existing or not-owning lock, so it seems an aftereffect from not being able to obtain the lock.
