### ISSUE TITLE
Cast Fuction fails with Mysql for Rest and Joex

### ISSUE THREAD

**Issue by sortedcord** [eikek/docspell#934]
I am using Docspell on a old computer with ubuntu 20.0 server without docker. I followed the steps mentioned on https://docspell.org/docs/configure/#jdbc and changed the database to mysql which I already had installed and setup. I created a database called `Library` and granted the user all privileges on it and accordingly changed the config file. 
However, when I run docspell, I always get a Mysql error that the `cast-function` failed. This happens both with rest and joex.

## Logs
```
[main] INFO  d.joex.Main - Using given config file: /home/codegrity/Development/docspell/docker/docker-compose/vu.conf
[main] INFO  d.joex.Main -
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.24.0 (#068281f9)
***>  << JOEX >>
***>  Id:       joex1
***>  Base-Url: http://localhost:7878
***>  Database: jdbc:mariadb://localhost:3306/Library
***>  Fts:      -
***>  Config:   vu.conf
***>
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations...
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/mariadb)
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.10.0 by Redgate
[ioapp-compute-0] INFO  o.f.c.i.d.b.BaseDatabaseType - Database: jdbc:mariadb://localhost:3306/Library (MySQL 8.0)
[ioapp-compute-0] INFO  o.f.c.i.c.DbRepair - Successfully repaired schema history table `Library`.`flyway_schema_history` (execution time 00:00.167s).
[ioapp-compute-0] INFO  o.f.c.i.c.DbRepair - Manual cleanup of the remaining effects of the failed migration may still be required.
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.10.0 by Redgate
[ioapp-compute-0] INFO  o.f.c.i.c.DbValidate - Successfully validated 37 migrations (execution time 00:00.026s)
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Current version of schema `Library`: 1.20.4
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Migrating schema `Library` to version "1.21.0 - cast function"
[ioapp-compute-0] ERROR o.f.c.i.c.DbMigrate - Migration of schema `Library` to version "1.21.0 - cast function" failed! Please restore backups and roll back database and code!
[ioapp-compute-0] INFO  o.h.c.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
Migration V1.21.0__cast_function.sql failed
-------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=50260) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
Location   : db/migration/mariadb/V1.21.0__cast_function.sql (/home/codegrity/Development/docspell/docker/docker-compose/file:/usr/share/docspell-joex/lib/com.github.eikek.docspell-store-0.24.0.jar!/db/migration/mariadb/V1.21.0__cast_function.sql)
Line       : 3
Statement  : -- Create a function to cast to a numeric, if an error occurs return null
-- Could not get it working with decimal type, so using double
create or replace function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(s as double)

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:357)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:262)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:261)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:140)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:156)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:219)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
        at org.flywaydb.core.Flyway.execute(Flyway.java:574)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
        at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:36)
        at map @ docspell.store.impl.StoreImpl.migrate(StoreImpl.scala:25)
        at eval @ docspell.joex.JoexServer$.stream(JoexServer.scala:31)
        at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
        at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$4(CompileScope.scala:185)
        at flatten @ fs2.internal.ScopedResource$$anon$1.acquired(ScopedResource.scala:139)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$1(CompileScope.scala:183)
        at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException:
Migration V1.21.0__cast_function.sql failed
-------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=50260) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
Location   : db/migration/mariadb/V1.21.0__cast_function.sql (/home/codegrity/Development/docspell/docker/docker-compose/file:/usr/share/docspell-joex/lib/com.github.eikek.docspell-store-0.24.0.jar!/db/migration/mariadb/V1.21.0__cast_function.sql)
Line       : 3
Statement  : -- Create a function to cast to a numeric, if an error occurs return null
-- Could not get it working with decimal type, so using double
create or replace function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(s as double)

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:277)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:224)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:354)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:262)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:261)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:140)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:156)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:219)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
        at org.flywaydb.core.Flyway.execute(Flyway.java:574)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
        at docspell.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:36)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
        at cats.effect.internals.IORunLoop$.restartCancelable(IORunLoop.scala:51)
        at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:100)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:80)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:58)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
        at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:41)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
        at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
        at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
        at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:447)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:156)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: (conn=50260) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:155)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212)
        ... 51 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
        ... 55 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function CAST_TO_NUMERIC (s char(255))
returns double deterministic
return cast(' at line 3
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
        ... 56 more
        ```

**Comment by eikek** [comment]
Hi @sortedcord , do you really use MySQL? MySQL is not supported, but MariaDB is. These two diverged a bit over the years. If it is MariaDB, which version are you using?

**Comment by sortedcord** [comment]
I have mysql installed but im making a db connection through the mariadb url... That's primarily because the ubuntu repositories have packages for mysql but no mariadb.

Here is the mysql version-
```mysql  Ver 8.0.25-0ubuntu0.21.04.1 for Linux on x86_64 ((Ubuntu))```

**Comment by eikek** [comment]
I'm afraid MySQL is not supported. Other options are PostgreSQL, which is recommended from my side. I find it strange, that Ubuntu has no MariaDB packages… I found [this](https://packages.ubuntu.com/hirsute/mariadb-server) which looks like such a package but I'm not using Ubuntu, so no idea really :-)

**Comment by sortedcord** [comment]
I was mistaken. Apparently there is a package for mariadb. So I did bit searched a bit for migrating ffrom mysql to mariadb. All of the sites that I had seen showed that the process was very simple, i.e, just stop the mysql service and install mariadb, however, it isn't working out for me. I might not have enough time to troubleshoot the issue so I will just backup all of my databases and do a fresh install with mariadb on ubuntu. I'll see how that goes.

**Comment by eikek** [comment]
I usually recommend PostgreSQL over MariaDB. I like it more personally, but to be fair, I used it way more often. But this still has some implications: I'm using Docspell with PostreSQL so bugs are more likely to go unnoticed in MariaDB. If you have the choice now anyways, I'd recommend postgres; if you have MariaDB running already, then I'd use this.
In terms of usage: PostgreSQL is also only a SQL database system. The CLI tools are a bit different, but if you know one it's usually not so hard to get used to the other.

**Comment by sortedcord** [comment]
I tried running the restserver using PostgreSQL and I get the following traceback-

```
➜  docspell git:(master) ✗ docspell-restserver rest.conf 
[main] INFO  d.r.Main - Using given config file: /home/codegrity/Development/docspell/rest.conf 
[main] INFO  d.r.Main - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.24.0 (#068281f9)
***>  << REST Server >>
***>  Id:       rest1
***>  Base-Url: http://localhost:7880
***>  Database: jdbc:postgresql://localhost:5432/docspelldb
***>  Fts:      -
***>  Config:   rest.conf
***>   
java.lang.ClassNotFoundException: org.postgresql.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at doobie.hikari.HikariTransactor$.$anonfun$newHikariTransactor$1(HikariTransactor.scala:58)
	at eval @ doobie.hikari.HikariTransactor$.newHikariTransactor(HikariTransactor.scala:58)
	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
```

Is it some missing dependency?
And this is the config block for reference
	
```
	jdbc {
      url = "jdbc:postgresql://localhost:5432/docspelldb"
      user = "sortedcord"
      password = "Sortedcord@94321"
    }
```

**Comment by eikek** [comment]
Oh! What java version are you using? (You can find out via `java -version`)

**Comment by sortedcord** [comment]
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

**Comment by eikek** [comment]
Ok, that is fine. And you are using the DEB files? It looks like a packaging bug to me currently. As a quick test/alternativ, you could download the zip files; then extract and start the same way.

**Comment by sortedcord** [comment]
That was the problem, it seems that there is some problem with the package. The binary in the zip file works

**Comment by sortedcord** [comment]
I think its quite similar to #716 In this case restserver works but joex does not...

**Comment by eikek** [comment]
This seems to be a permission problem. The other ticket is about a race condition when upgrading the database schema. Could you chekc the permissions and owner of `/tmp/docspell-analysis`. Or you can stop docspell, remove this directory and start it again. I suspect that this is left over from the run using the deb files, which run under teh user `docspell`. And now, it's running under your user.

**Comment by sortedcord** [comment]
Deleting the folder did the trick. Thank You!
